In [3]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = None

In [4]:
!pwd

/home/dsc/CarpetaCompartida/TFM

In [5]:
path_2013 = "/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/PFMDIASM_TOD_2013"

In [6]:
jan2013 = pd.read_excel(path_2013 + "01.2/PFMDIASM_TOD_20130101_20130131.xls", 
                      dtype= str,parse_dates= True, engine= None, header = 3)

jan2013.head()

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh
0,01/01/13 Martes,575111.397,33.31,0.43,6.08,2.49,5.11,47.42
1,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65
2,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67
3,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73
4,05/01/13 Sábado,682149.96,58.11,0.14,1.29,1.43,4.88,65.86

In [7]:
jan2013

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh
0,01/01/13 Martes,575111.397,33.31,0.43,6.08,2.49,5.11,47.42
1,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65
2,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67
3,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73
4,05/01/13 Sábado,682149.96,58.11,0.14,1.29,1.43,4.88,65.86
5,06/01/13 Domingo,647854.785,58.01,0,2.27,2.16,5.02,67.45
6,07/01/13 Lunes,707896.584,63.42,-0.18,2.45,2.57,7.26,75.52
7,08/01/13 Martes,792239.818,69,0.08,1.21,1.94,7.43,79.65
8,09/01/13 Miércoles,813192.864,67.43,0.05,1.74,1.08,7.32,77.62
9,10/01/13 Jueves,821426.583,66.12,0.09,1.45,1.63,7.17,76.45
10,11/01/13 Viernes,798185.741,72.41,-0.07,0.84,1.05,7.2,81.41
11,12/01/13 Sábado,740278.669,54,0.03,1.51,1.52,4.71,61.76
12,13/01/13 Domingo,749513.927,46.55,-0.13,2.62,1.45,4.73,55.22
13,14/01/13 Lunes,836521.045,62.86,-0.05,1.99,1.84,7.34,73.98
14,15/01/13 Martes,834049.052,58.89,-0.03,2.01,1.19,7.14,69.2
15,16/01/13 Miércoles,848523.814,52.11,-0.07,2.6,1.05,7.05,62.74
16,17/01/13 Jueves,835820.933,53.45,-0.01,1.7,2.07,6.98,64.19
17,18/01/13 Viernes,821497.905,50.7,-0.22,2.43,1.6,6.96,61.48
18,19/01/13 Sábado,773058.96,38.98,-0.16,3.24,1.84,4.49,48.37
19,20/01/13 Domingo,758725.093,21.54,-0.01,3.51,2.98,4.56,32.57
20,21/01/13 Lunes,846241.962,46.19,-0.05,3.24,2.84,7.09,59.31
21,22/01/13 Martes,849699.509,38.22,0.05,4.81,2.44,7.06,52.58
22,23/01/13 Miércoles,854451.878,40.93,-0.12,3.27,2.19,6.99,53.26
23,24/01/13 Jueves,833700.982,42.71,0.02,3.28,2.73,7.04,55.78
24,25/01/13 Viernes,799322.834,61.14,0.04,2.16,2.77,7.16,73.28
25,26/01/13 Sábado,756533.728,41.44,-0.04,1.96,2.48,4.45,50.29
26,27/01/13 Domingo,747290.908,36.03,-0.07,1.88,2.89,4.55,45.28
27,28/01/13 Lunes,822034.663,48.7,-0.18,2.63,2.24,7.13,60.51
28,29/01/13 Martes,784054.319,55.08,-0.06,2.19,1.89,7.22,66.32
29,30/01/13 Miércoles,791956.086,51.43,-0.15,2.06,2.38,7.08,62.81
30,31/01/13 Jueves,783856.72,58.82,-0.48,2.3,2.5,7.09,70.22

In [8]:
jan2013.dtypes

Periodo                                       object
Energía\n final \nMWh                         object
Mercado \ndiario \n€/MWh                      object
Mercado \nintradiario \n€/MWh                 object
Restricciones\n€/MWh                          object
Procesos \nOS \n€/MWh                         object
Garantía potencia \nPagos capacidad\n€/MWh    object
Total\n€/MWh                                  object
dtype: object

In [9]:
jan2013[["Date", "Day"]] = jan2013.Periodo.str.split(expand= True)

In [10]:
jan2013

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh,Date,Day
0,01/01/13 Martes,575111.397,33.31,0.43,6.08,2.49,5.11,47.42,01/01/13,Martes
1,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65,02/01/13,Miércoles
2,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67,03/01/13,Jueves
3,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73,04/01/13,Viernes
4,05/01/13 Sábado,682149.96,58.11,0.14,1.29,1.43,4.88,65.86,05/01/13,Sábado
5,06/01/13 Domingo,647854.785,58.01,0,2.27,2.16,5.02,67.45,06/01/13,Domingo
6,07/01/13 Lunes,707896.584,63.42,-0.18,2.45,2.57,7.26,75.52,07/01/13,Lunes
7,08/01/13 Martes,792239.818,69,0.08,1.21,1.94,7.43,79.65,08/01/13,Martes
8,09/01/13 Miércoles,813192.864,67.43,0.05,1.74,1.08,7.32,77.62,09/01/13,Miércoles
9,10/01/13 Jueves,821426.583,66.12,0.09,1.45,1.63,7.17,76.45,10/01/13,Jueves
10,11/01/13 Viernes,798185.741,72.41,-0.07,0.84,1.05,7.2,81.41,11/01/13,Viernes
11,12/01/13 Sábado,740278.669,54,0.03,1.51,1.52,4.71,61.76,12/01/13,Sábado
12,13/01/13 Domingo,749513.927,46.55,-0.13,2.62,1.45,4.73,55.22,13/01/13,Domingo
13,14/01/13 Lunes,836521.045,62.86,-0.05,1.99,1.84,7.34,73.98,14/01/13,Lunes
14,15/01/13 Martes,834049.052,58.89,-0.03,2.01,1.19,7.14,69.2,15/01/13,Martes
15,16/01/13 Miércoles,848523.814,52.11,-0.07,2.6,1.05,7.05,62.74,16/01/13,Miércoles
16,17/01/13 Jueves,835820.933,53.45,-0.01,1.7,2.07,6.98,64.19,17/01/13,Jueves
17,18/01/13 Viernes,821497.905,50.7,-0.22,2.43,1.6,6.96,61.48,18/01/13,Viernes
18,19/01/13 Sábado,773058.96,38.98,-0.16,3.24,1.84,4.49,48.37,19/01/13,Sábado
19,20/01/13 Domingo,758725.093,21.54,-0.01,3.51,2.98,4.56,32.57,20/01/13,Domingo
20,21/01/13 Lunes,846241.962,46.19,-0.05,3.24,2.84,7.09,59.31,21/01/13,Lunes
21,22/01/13 Martes,849699.509,38.22,0.05,4.81,2.44,7.06,52.58,22/01/13,Martes
22,23/01/13 Miércoles,854451.878,40.93,-0.12,3.27,2.19,6.99,53.26,23/01/13,Miércoles
23,24/01/13 Jueves,833700.982,42.71,0.02,3.28,2.73,7.04,55.78,24/01/13,Jueves
24,25/01/13 Viernes,799322.834,61.14,0.04,2.16,2.77,7.16,73.28,25/01/13,Viernes
25,26/01/13 Sábado,756533.728,41.44,-0.04,1.96,2.48,4.45,50.29,26/01/13,Sábado
26,27/01/13 Domingo,747290.908,36.03,-0.07,1.88,2.89,4.55,45.28,27/01/13,Domingo
27,28/01/13 Lunes,822034.663,48.7,-0.18,2.63,2.24,7.13,60.51,28/01/13,Lunes
28,29/01/13 Martes,784054.319,55.08,-0.06,2.19,1.89,7.22,66.32,29/01/13,Martes
29,30/01/13 Miércoles,791956.086,51.43,-0.15,2.06,2.38,7.08,62.81,30/01/13,Miércoles
30,31/01/13 Jueves,783856.72,58.82,-0.48,2.3,2.5,7.09,70.22,31/01/13,Jueves

In [11]:
jan2013.dtypes

Periodo                                       object
Energía\n final \nMWh                         object
Mercado \ndiario \n€/MWh                      object
Mercado \nintradiario \n€/MWh                 object
Restricciones\n€/MWh                          object
Procesos \nOS \n€/MWh                         object
Garantía potencia \nPagos capacidad\n€/MWh    object
Total\n€/MWh                                  object
Date                                          object
Day                                           object
dtype: object

In [12]:
jan2013["Date"] = pd.to_datetime(jan2013["Date"])

In [13]:
jan2013.dtypes

Periodo                                               object
Energía\n final \nMWh                                 object
Mercado \ndiario \n€/MWh                              object
Mercado \nintradiario \n€/MWh                         object
Restricciones\n€/MWh                                  object
Procesos \nOS \n€/MWh                                 object
Garantía potencia \nPagos capacidad\n€/MWh            object
Total\n€/MWh                                          object
Date                                          datetime64[ns]
Day                                                   object
dtype: object

In [14]:
jan2013.head()

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh,Date,Day
0,01/01/13 Martes,575111.397,33.31,0.43,6.08,2.49,5.11,47.42,2013-01-01,Martes
1,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65,2013-02-01,Miércoles
2,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67,2013-03-01,Jueves
3,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73,2013-04-01,Viernes
4,05/01/13 Sábado,682149.96,58.11,0.14,1.29,1.43,4.88,65.86,2013-05-01,Sábado

In [15]:
import glob

In [16]:
data2013_import = glob.glob("/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_2013*xls")
print(data2013_import)

['/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20130101_20130131.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20130201_20130228.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20130301_20130331.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20130401_20130430.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20130501_20130531.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20130601_20130630.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20130701_20130731.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20130801_20130831.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20130901_20130930.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20131001_20131031.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20131101_20131130.xls', '/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_20131201_20131231.xls']

In [17]:
#This doesn't work because it returns a list, not a Dataframe

data2013 = []

for filename in data2013_import:
    data= pd.read_excel(filename, dtype= str,parse_dates= True, engine= None, header = 3)
    data2013.append(data)
    
data2013

pd.concat(data2013, ignore_index= True)

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh
0,01/01/13 Martes,575111.397,33.31,0.43,6.08,2.49,5.11,47.42
1,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65
2,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67
3,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73
4,05/01/13 Sábado,682149.96,58.11,0.14,1.29,1.43,4.88,65.86
...,...,...,...,...,...,...,...,...
360,27/12/13 Viernes,663171.045,15.39,0,5.62,5.04,6.82,32.88
361,28/12/13 Sábado,672714.85,23.98,0.01,5.34,3.21,4.46,37
362,29/12/13 Domingo,634045.486,42.83,-0.13,5.28,2.88,4.81,55.66
363,30/12/13 Lunes,634951.745,47.39,-0.57,5.5,4.2,7.33,63.85
364,31/12/13 Martes,606765.004,25.26,-0.15,8.44,5.59,6.79,45.93

In [18]:
type(data2013)

list

In [19]:
#Using glob.iglob() it returns an iterator that I can easily convert into a pandas Dataframe
data2013_import = glob.iglob("/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Definitivo_2013/2013/PFMDIASM_TOD_2013*xls")
print(data2013_import)

dataframes = (pd.read_excel(excel, dtype= str,parse_dates= True, engine= None, header = 3) for excel in data2013_import)

data2013  = pd.concat(dataframes, ignore_index= True)

<generator object _iglob at 0x7fd8afe4f970>

In [20]:
data2013

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh
0,01/01/13 Martes,575111.397,33.31,0.43,6.08,2.49,5.11,47.42
1,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65
2,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67
3,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73
4,05/01/13 Sábado,682149.96,58.11,0.14,1.29,1.43,4.88,65.86
...,...,...,...,...,...,...,...,...
360,27/12/13 Viernes,663171.045,15.39,0,5.62,5.04,6.82,32.88
361,28/12/13 Sábado,672714.85,23.98,0.01,5.34,3.21,4.46,37
362,29/12/13 Domingo,634045.486,42.83,-0.13,5.28,2.88,4.81,55.66
363,30/12/13 Lunes,634951.745,47.39,-0.57,5.5,4.2,7.33,63.85
364,31/12/13 Martes,606765.004,25.26,-0.15,8.44,5.59,6.79,45.93

In [21]:
type(data2013)

pandas.core.frame.DataFrame

In [22]:
data2013[["Date", "Day"]] = data2013.Periodo.str.split(expand= True)

In [23]:
data2013.head()

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh,Date,Day
0,01/01/13 Martes,575111.397,33.31,0.43,6.08,2.49,5.11,47.42,01/01/13,Martes
1,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65,02/01/13,Miércoles
2,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67,03/01/13,Jueves
3,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73,04/01/13,Viernes
4,05/01/13 Sábado,682149.96,58.11,0.14,1.29,1.43,4.88,65.86,05/01/13,Sábado

In [24]:
data2013["Date"] = pd.to_datetime(data2013["Date"])

In [25]:
brent_prices = pd.read_csv("/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Datos_históricos_Futuros_petróleo_Brent.csv")
brent_prices

           Fecha  Último Apertura  Máximo  Mínimo     Vol.  % var.
0     16.07.2021   73,59    73,18   74,09   72,34  292,66K   0,16%
1     15.07.2021   73,47    74,50   74,59   73,19  322,33K  -1,73%
2     14.07.2021   74,76    76,28   76,72   73,79  376,94K  -2,26%
3     13.07.2021   76,49    75,25   76,60   74,93  275,91K   1,77%
4     12.07.2021   75,16    75,79   75,84   74,23  262,30K  -0,52%
...          ...     ...      ...     ...     ...      ...     ...
2200  08.01.2013  111,94   111,42  112,47  111,12  194,00K   0,48%
2201  07.01.2013  111,40   111,42  111,69  110,54  203,50K   0,08%
2202  04.01.2013  111,31   111,72  111,78  110,38  191,33K  -0,74%
2203  03.01.2013  112,14   112,20  112,42  111,63  190,29K  -0,29%
2204  02.01.2013  112,47   111,50  112,90  111,27  183,14K   1,22%

[2205 rows x 7 columns]

In [26]:
brent_prices.dtypes

Fecha       object
Último      object
Apertura    object
Máximo      object
Mínimo      object
Vol.        object
% var.      object
dtype: object

In [27]:
brent_prices["Fecha"] = pd.to_datetime(brent_prices["Fecha"])

In [28]:
#Column "Vol." is the number of contracts that were sold that day
brent_prices

          Fecha  Último Apertura  Máximo  Mínimo     Vol.  % var.
0    2021-07-16   73,59    73,18   74,09   72,34  292,66K   0,16%
1    2021-07-15   73,47    74,50   74,59   73,19  322,33K  -1,73%
2    2021-07-14   74,76    76,28   76,72   73,79  376,94K  -2,26%
3    2021-07-13   76,49    75,25   76,60   74,93  275,91K   1,77%
4    2021-12-07   75,16    75,79   75,84   74,23  262,30K  -0,52%
...         ...     ...      ...     ...     ...      ...     ...
2200 2013-08-01  111,94   111,42  112,47  111,12  194,00K   0,48%
2201 2013-07-01  111,40   111,42  111,69  110,54  203,50K   0,08%
2202 2013-04-01  111,31   111,72  111,78  110,38  191,33K  -0,74%
2203 2013-03-01  112,14   112,20  112,42  111,63  190,29K  -0,29%
2204 2013-02-01  112,47   111,50  112,90  111,27  183,14K   1,22%

[2205 rows x 7 columns]

In [29]:
brent_prices.dtypes

Fecha       datetime64[ns]
Último              object
Apertura            object
Máximo              object
Mínimo              object
Vol.                object
% var.              object
dtype: object

In [30]:
brent_prices.rename(columns={"Fecha":"Date"}, inplace= True)

In [31]:
brent_prices

           Date  Último Apertura  Máximo  Mínimo     Vol.  % var.
0    2021-07-16   73,59    73,18   74,09   72,34  292,66K   0,16%
1    2021-07-15   73,47    74,50   74,59   73,19  322,33K  -1,73%
2    2021-07-14   74,76    76,28   76,72   73,79  376,94K  -2,26%
3    2021-07-13   76,49    75,25   76,60   74,93  275,91K   1,77%
4    2021-12-07   75,16    75,79   75,84   74,23  262,30K  -0,52%
...         ...     ...      ...     ...     ...      ...     ...
2200 2013-08-01  111,94   111,42  112,47  111,12  194,00K   0,48%
2201 2013-07-01  111,40   111,42  111,69  110,54  203,50K   0,08%
2202 2013-04-01  111,31   111,72  111,78  110,38  191,33K  -0,74%
2203 2013-03-01  112,14   112,20  112,42  111,63  190,29K  -0,29%
2204 2013-02-01  112,47   111,50  112,90  111,27  183,14K   1,22%

[2205 rows x 7 columns]

In [32]:
prices2013_brent = pd.merge(data2013, brent_prices, on= "Date", sort=False, indicator= True)
prices2013_brent

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh,Date,Day,Último,Apertura,Máximo,Mínimo,Vol.,% var.,_merge
0,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65,2013-02-01,Miércoles,"112,47","111,50","112,90","111,27","183,14K","1,22%",both
1,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67,2013-03-01,Jueves,"112,14","112,20","112,42","111,63","190,29K","-0,29%",both
2,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73,2013-04-01,Viernes,"111,31","111,72","111,78","110,38","191,33K","-0,74%",both
3,07/01/13 Lunes,707896.584,63.42,-0.18,2.45,2.57,7.26,75.52,2013-07-01,Lunes,"111,40","111,42","111,69","110,54","203,50K","0,08%",both
4,08/01/13 Martes,792239.818,69,0.08,1.21,1.94,7.43,79.65,2013-08-01,Martes,"111,94","111,42","112,47","111,12","194,00K","0,48%",both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,24/12/13 Martes,627047.199,9.63,-0.13,6.27,8.01,6.59,30.36,2013-12-24,Martes,"111,90","111,61","112,06","111,42","52,16K","0,30%",both
254,26/12/13 Jueves,659881.358,14.18,-0.36,7.17,4.37,6.71,32.07,2013-12-26,Jueves,"111,98","111,99","112,12","111,46","43,62K","0,07%",both
255,27/12/13 Viernes,663171.045,15.39,0,5.62,5.04,6.82,32.88,2013-12-27,Viernes,"112,18","111,95","112,80","111,50","126,91K","0,18%",both
256,30/12/13 Lunes,634951.745,47.39,-0.57,5.5,4.2,7.33,63.85,2013-12-30,Lunes,"111,21","112,20","112,64","110,90","111,07K","-0,86%",both
257,31/12/13 Martes,606765.004,25.26,-0.15,8.44,5.59,6.79,45.93,2013-12-31,Martes,"110,80","111,18","111,52","110,40","84,99K","-0,37%",both

In [33]:
brent_prices["Date"]

0      2021-07-16
1      2021-07-15
2      2021-07-14
3      2021-07-13
4      2021-12-07
          ...
2200   2013-08-01
2201   2013-07-01
2202   2013-04-01
2203   2013-03-01
2204   2013-02-01
Name: Date, Length: 2205, dtype: datetime64[ns]

In [34]:
brent_prices = brent_prices.set_index(["Date"])
brent_2013 = brent_prices.loc['2013-01-01':'2013-12-31']
print(brent_2013)

            Último Apertura  Máximo  Mínimo     Vol.  % var.
Date
2013-12-31  110,80   111,18  111,52  110,40   84,99K  -0,37%
2013-12-30  111,21   112,20  112,64  110,90  111,07K  -0,86%
2013-12-27  112,18   111,95  112,80  111,50  126,91K   0,18%
2013-12-26  111,98   111,99  112,12  111,46   43,62K   0,07%
2013-12-24  111,90   111,61  112,06  111,42   52,16K   0,30%
...            ...      ...     ...     ...      ...     ...
2013-08-01  111,94   111,42  112,47  111,12  194,00K   0,48%
2013-07-01  111,40   111,42  111,69  110,54  203,50K   0,08%
2013-04-01  111,31   111,72  111,78  110,38  191,33K  -0,74%
2013-03-01  112,14   112,20  112,42  111,63  190,29K  -0,29%
2013-02-01  112,47   111,50  112,90  111,27  183,14K   1,22%

[258 rows x 6 columns]

In [35]:
#In the brent_prices DataFrame, we're missing Saturday and Sunday prices (and bank holidays) 
#This is because the Brent Crude Futures Markets does not operate during weekends.
#So Friday prices should also be Saturday and Sunday prices.

prices2013_brent["Day"].unique()

array(['Miércoles', 'Jueves', 'Viernes', 'Lunes', 'Martes'], dtype=object)

In [36]:
date_day = data2013[["Date", "Day"]]
date_day

          Date        Day
0   2013-01-01     Martes
1   2013-02-01  Miércoles
2   2013-03-01     Jueves
3   2013-04-01    Viernes
4   2013-05-01     Sábado
..         ...        ...
360 2013-12-27    Viernes
361 2013-12-28     Sábado
362 2013-12-29    Domingo
363 2013-12-30      Lunes
364 2013-12-31     Martes

[365 rows x 2 columns]

In [37]:
brent_prices_allweek = pd.merge(date_day, brent_prices, on= "Date", indicator = True, how= "left")
brent_prices_allweek

,Date,Day,Último,Apertura,Máximo,Mínimo,Vol.,% var.,_merge
0,2013-01-01,Martes,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,2013-02-01,Miércoles,"112,47","111,50","112,90","111,27","183,14K","1,22%",both
2,2013-03-01,Jueves,"112,14","112,20","112,42","111,63","190,29K","-0,29%",both
3,2013-04-01,Viernes,"111,31","111,72","111,78","110,38","191,33K","-0,74%",both
4,2013-05-01,Sábado,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...
360,2013-12-27,Viernes,"112,18","111,95","112,80","111,50","126,91K","0,18%",both
361,2013-12-28,Sábado,NaN,NaN,NaN,NaN,NaN,NaN,left_only
362,2013-12-29,Domingo,NaN,NaN,NaN,NaN,NaN,NaN,left_only
363,2013-12-30,Lunes,"111,21","112,20","112,64","110,90","111,07K","-0,86%",both
364,2013-12-31,Martes,"110,80","111,18","111,52","110,40","84,99K","-0,37%",both

In [38]:
#There were 107 Saturday, Sunday and bank holidays in 2013 in Spain
np.count_nonzero(brent_prices_allweek["_merge"] != "both")

107

In [39]:
weekends_holidays_index = brent_prices_allweek[brent_prices_allweek["_merge"] != "both"].index.tolist()
weekends_holidays_index

[0,
 4,
 5,
 11,
 12,
 18,
 19,
 25,
 26,
 32,
 33,
 39,
 40,
 46,
 47,
 53,
 54,
 60,
 61,
 67,
 68,
 74,
 75,
 81,
 82,
 87,
 88,
 89,
 95,
 96,
 102,
 103,
 109,
 110,
 116,
 117,
 123,
 124,
 130,
 131,
 137,
 138,
 144,
 145,
 151,
 152,
 158,
 159,
 165,
 166,
 172,
 173,
 179,
 180,
 186,
 187,
 193,
 194,
 200,
 201,
 207,
 208,
 214,
 215,
 221,
 222,
 228,
 229,
 235,
 236,
 242,
 243,
 249,
 250,
 256,
 257,
 263,
 264,
 270,
 271,
 277,
 278,
 284,
 285,
 291,
 292,
 298,
 299,
 305,
 306,
 312,
 313,
 319,
 320,
 326,
 327,
 333,
 334,
 340,
 341,
 347,
 348,
 354,
 355,
 358,
 361,
 362]

In [40]:
brent_prices_allweek = brent_prices_allweek.fillna(method= "ffill")
brent_prices_allweek

,Date,Day,Último,Apertura,Máximo,Mínimo,Vol.,% var.,_merge
0,2013-01-01,Martes,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,2013-02-01,Miércoles,"112,47","111,50","112,90","111,27","183,14K","1,22%",both
2,2013-03-01,Jueves,"112,14","112,20","112,42","111,63","190,29K","-0,29%",both
3,2013-04-01,Viernes,"111,31","111,72","111,78","110,38","191,33K","-0,74%",both
4,2013-05-01,Sábado,"111,31","111,72","111,78","110,38","191,33K","-0,74%",left_only
...,...,...,...,...,...,...,...,...,...
360,2013-12-27,Viernes,"112,18","111,95","112,80","111,50","126,91K","0,18%",both
361,2013-12-28,Sábado,"112,18","111,95","112,80","111,50","126,91K","0,18%",left_only
362,2013-12-29,Domingo,"112,18","111,95","112,80","111,50","126,91K","0,18%",left_only
363,2013-12-30,Lunes,"111,21","112,20","112,64","110,90","111,07K","-0,86%",both
364,2013-12-31,Martes,"110,80","111,18","111,52","110,40","84,99K","-0,37%",both

In [41]:
#The 1st of January of 2013 still has NaN values, but I don't have historical data before that.
#Therefore, I'll drop that row
brent_prices_allweek.isna().sum()

Date        0
Day         0
Último      1
Apertura    1
Máximo      1
Mínimo      1
Vol.        1
% var.      1
_merge      0
dtype: int64

In [42]:
brent_prices_allweek = brent_prices_allweek.dropna()
brent_prices_allweek

,Date,Day,Último,Apertura,Máximo,Mínimo,Vol.,% var.,_merge
1,2013-02-01,Miércoles,"112,47","111,50","112,90","111,27","183,14K","1,22%",both
2,2013-03-01,Jueves,"112,14","112,20","112,42","111,63","190,29K","-0,29%",both
3,2013-04-01,Viernes,"111,31","111,72","111,78","110,38","191,33K","-0,74%",both
4,2013-05-01,Sábado,"111,31","111,72","111,78","110,38","191,33K","-0,74%",left_only
5,2013-06-01,Domingo,"111,31","111,72","111,78","110,38","191,33K","-0,74%",left_only
...,...,...,...,...,...,...,...,...,...
360,2013-12-27,Viernes,"112,18","111,95","112,80","111,50","126,91K","0,18%",both
361,2013-12-28,Sábado,"112,18","111,95","112,80","111,50","126,91K","0,18%",left_only
362,2013-12-29,Domingo,"112,18","111,95","112,80","111,50","126,91K","0,18%",left_only
363,2013-12-30,Lunes,"111,21","112,20","112,64","110,90","111,07K","-0,86%",both
364,2013-12-31,Martes,"110,80","111,18","111,52","110,40","84,99K","-0,37%",both

In [43]:
prices2013_brent = pd.merge(data2013, brent_prices_allweek, on= "Date", sort=False)
prices2013_brent

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh,Date,Day_x,Day_y,Último,Apertura,Máximo,Mínimo,Vol.,% var.,_merge
0,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65,2013-02-01,Miércoles,Miércoles,"112,47","111,50","112,90","111,27","183,14K","1,22%",both
1,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67,2013-03-01,Jueves,Jueves,"112,14","112,20","112,42","111,63","190,29K","-0,29%",both
2,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73,2013-04-01,Viernes,Viernes,"111,31","111,72","111,78","110,38","191,33K","-0,74%",both
3,05/01/13 Sábado,682149.96,58.11,0.14,1.29,1.43,4.88,65.86,2013-05-01,Sábado,Sábado,"111,31","111,72","111,78","110,38","191,33K","-0,74%",left_only
4,06/01/13 Domingo,647854.785,58.01,0,2.27,2.16,5.02,67.45,2013-06-01,Domingo,Domingo,"111,31","111,72","111,78","110,38","191,33K","-0,74%",left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,27/12/13 Viernes,663171.045,15.39,0,5.62,5.04,6.82,32.88,2013-12-27,Viernes,Viernes,"112,18","111,95","112,80","111,50","126,91K","0,18%",both
360,28/12/13 Sábado,672714.85,23.98,0.01,5.34,3.21,4.46,37,2013-12-28,Sábado,Sábado,"112,18","111,95","112,80","111,50","126,91K","0,18%",left_only
361,29/12/13 Domingo,634045.486,42.83,-0.13,5.28,2.88,4.81,55.66,2013-12-29,Domingo,Domingo,"112,18","111,95","112,80","111,50","126,91K","0,18%",left_only
362,30/12/13 Lunes,634951.745,47.39,-0.57,5.5,4.2,7.33,63.85,2013-12-30,Lunes,Lunes,"111,21","112,20","112,64","110,90","111,07K","-0,86%",both
363,31/12/13 Martes,606765.004,25.26,-0.15,8.44,5.59,6.79,45.93,2013-12-31,Martes,Martes,"110,80","111,18","111,52","110,40","84,99K","-0,37%",both

In [44]:
prices2013_brent = prices2013_brent.drop(columns= ["Day_y", "_merge", "% var."])
prices2013_brent.rename(columns={"Day_x":"Day"}, inplace= True)
prices2013_brent

,Periodo,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh,Date,Day,Último,Apertura,Máximo,Mínimo,Vol.
0,02/01/13 Miércoles,681911.324,50.75,0.12,3.15,3.18,7.46,64.65,2013-02-01,Miércoles,"112,47","111,50","112,90","111,27","183,14K"
1,03/01/13 Jueves,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67,2013-03-01,Jueves,"112,14","112,20","112,42","111,63","190,29K"
2,04/01/13 Viernes,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73,2013-04-01,Viernes,"111,31","111,72","111,78","110,38","191,33K"
3,05/01/13 Sábado,682149.96,58.11,0.14,1.29,1.43,4.88,65.86,2013-05-01,Sábado,"111,31","111,72","111,78","110,38","191,33K"
4,06/01/13 Domingo,647854.785,58.01,0,2.27,2.16,5.02,67.45,2013-06-01,Domingo,"111,31","111,72","111,78","110,38","191,33K"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,27/12/13 Viernes,663171.045,15.39,0,5.62,5.04,6.82,32.88,2013-12-27,Viernes,"112,18","111,95","112,80","111,50","126,91K"
360,28/12/13 Sábado,672714.85,23.98,0.01,5.34,3.21,4.46,37,2013-12-28,Sábado,"112,18","111,95","112,80","111,50","126,91K"
361,29/12/13 Domingo,634045.486,42.83,-0.13,5.28,2.88,4.81,55.66,2013-12-29,Domingo,"112,18","111,95","112,80","111,50","126,91K"
362,30/12/13 Lunes,634951.745,47.39,-0.57,5.5,4.2,7.33,63.85,2013-12-30,Lunes,"111,21","112,20","112,64","110,90","111,07K"
363,31/12/13 Martes,606765.004,25.26,-0.15,8.44,5.59,6.79,45.93,2013-12-31,Martes,"110,80","111,18","111,52","110,40","84,99K"

In [45]:
#The encoding = "latin1" is used so "special characters" like ñ is read well

listado_estaciones = pd.read_csv("/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Aemet2021-06-Por-Estaciones/ListadoEstaciones.csv", 
                                names =["Identificador_est", "Nombre_est", "Municipio", "Provincia", "Altura", "Longitud", "Latitud"],
                                         header= 0, dtype = str, engine= "python", sep=";", error_bad_lines= False,
                                encoding= "latin1")
listado_estaciones

,Identificador_est,Nombre_est,Municipio,Provincia,Altura,Longitud,Latitud
0,1387,A Coruña,"Coruña, A",A Coruña,58,432157N,082517W
1,1387E,A Coruña Aeropuerto,Culleredo,A Coruña,98,431825N,082219W
2,1390X,"Carballo, Depuradora",Carballo,A Coruña,98,431213N,084239W
3,1393,Cabo Vilan,Camariñas,A Coruña,50,430938N,091239W
4,1399,Vimianzo,Vimianzo,A Coruña,287,430327N,090249W
...,...,...,...,...,...,...,...
843,B640X,Petra,Petra,Illes Balears,95,393659N,030716E
844,9293X,"Alfaro, La Plana",Alfaro,La Rioja,371,421034N,014438W
845,9445L,"Formigal, Sarrios",Sallent de Gállego,Huesca,1800,424545N,002334W
846,9574B,"Caspe, Plana del Pilón",Caspe,Zaragoza,202,411433N,000407W
847,1387D,A Coruña Bens,"Coruña, A",A Coruña,132,432148N,082631W

I want to choose some weather stations that could represent the different temperatures across Spain (peninsula). So I have checked the most extreme latitude and longitude in the peninsula to pick some around there. 

![title](Lat_lon_extreme.PNG)

Also, looking at the map, let's choose some more stations in some provincies across the Spanish territory:

![title](Mapa-de-las-provincias-de-Espana.png)

In [46]:
listado_estaciones.iloc[4]["Longitud"]

'430327N'

In [47]:
in_coruña = listado_estaciones["Provincia"] == "A Coruña"
in_coruña

0       True
1       True
2       True
3       True
4       True
       ...
843    False
844    False
845    False
846    False
847     True
Name: Provincia, Length: 848, dtype: bool

In [48]:
estaciones_coruña = listado_estaciones[in_coruña]
estaciones_coruña

,Identificador_est,Nombre_est,Municipio,Provincia,Altura,Longitud,Latitud
0,1387,A Coruña,"Coruña, A",A Coruña,58,432157N,082517W
1,1387E,A Coruña Aeropuerto,Culleredo,A Coruña,98,431825N,082219W
2,1390X,"Carballo, Depuradora",Carballo,A Coruña,98,431213N,084239W
3,1393,Cabo Vilan,Camariñas,A Coruña,50,430938N,091239W
4,1399,Vimianzo,Vimianzo,A Coruña,287,430327N,090249W
5,1400,Fisterra,Fisterra,A Coruña,230,425529N,091729W
6,1406X,Mazaricos,Mazaricos,A Coruña,340,425607N,085937W
7,1410X,Sobrado,Sobrado,A Coruña,500,430216N,080120W
8,1428,Santiago de Compostela Aeropuerto,"Pino, O",A Coruña,370,425317N,082438W
9,1435C,Noia,Noia,A Coruña,128,424801N,085234W
10,1437O,Monte Iroite,Porto do Son,A Coruña,685,424314N,085524W
11,1442U,Boiro,Boiro,A Coruña,10,423838N,085332W
12,1473A,Padrón,Padrón,A Coruña,100,424418N,083738W
13,1475X,Santiago de Compostela,Santiago de Compostela,A Coruña,240,425234N,083321W
14,1476R,"Rois, Casas do Porto",Rois,A Coruña,210,424459N,084253W
798,1351,Estaca de Bares,Mañón,A Coruña,80,434710N,074105W
835,1354C,Ferrol,Ferrol,A Coruña,4,432835N,081533W
847,1387D,A Coruña Bens,"Coruña, A",A Coruña,132,432148N,082631W

In [49]:
in_cadiz = listado_estaciones["Provincia"] == "Cádiz"
in_cadiz
estaciones_cadiz = listado_estaciones[in_cadiz]
estaciones_cadiz

,Identificador_est,Nombre_est,Municipio,Provincia,Altura,Longitud,Latitud
187,5906X,Chipiona,Chipiona,Cádiz,10,364500N,062402W
188,5910X,"Rota, Base Naval",Rota,Cádiz,21,363820N,061957W
189,5911A,Grazalema,Grazalema,Cádiz,913,364538N,052227W
190,5919X,Olvera,Olvera,Cádiz,530,365554N,051534W
191,5941X,El Bosque,"Bosque, El",Cádiz,295,364346N,053044W
192,5950X,San José del Valle,San José del Valle,Cádiz,105,363950N,054700W
193,5960,Jerez de la Frontera Aeropuerto,Jerez de la Frontera,Cádiz,27,364502N,060321W
194,5972X,San Fernando,San Fernando,Cádiz,28,362756N,061220W
195,5973,Cádiz,Cádiz,Cádiz,2,362959N,061528W
196,5983X,Medina Sidonia,Medina-Sidonia,Cádiz,70,362423N,055513W
197,5995B,Vejer de la Frontera,Vejer de la Frontera,Cádiz,186,361444N,055754W
198,5996B,Barbate,Barbate,Cádiz,4,361106N,055435W
199,6001,Tarifa,Tarifa,Cádiz,32,360050N,053556W
200,6042I,Jimena de la Frontera,Jimena de la Frontera,Cádiz,42,362608N,052342W
201,6056X,San Roque,San Roque,Cádiz,1,361623N,051704W

In [50]:
in_gerona = listado_estaciones["Provincia"] == "Girona"
in_gerona
estaciones_gerona = listado_estaciones[in_gerona]
estaciones_gerona

,Identificador_est,Nombre_est,Municipio,Provincia,Altura,Longitud,Latitud
283,0281Y,Blanes,Blanes,Girona,45,414037N,024818E
284,0284X,"Castell, Platja d`Aro","Castell, Platja d`Aro",Girona,14,414828N,030151E
285,0312X,Sant Pau de Segúries,Sant Pau de Segúries,Girona,851,421530N,022152E
286,0320I,Planoles,Planoles,Girona,1151,421901N,020610E
287,0324A,Ripoll,Ripoll,Girona,675,421129N,021146E
288,0360X,Les Planes d'Hostoles,"Planes d'Hostoles, Les",Girona,322,420310N,023304E
289,0363X,Sant Hilari,Sant Hilari Sacalm,Girona,810,415251N,023048E
290,0367,Girona Aeropuerto,Vilobí d'Onyar,Girona,143,415442N,024548E
291,0370E,Girona,Girona,Girona,76,415820N,024910E
292,0372C,Porqueres,Porqueres,Girona,157,420616N,024549E
293,0385X,L'Estartit,Torroella de Montgrí,Girona,1,420314N,031205E
294,0394X,La Vall de Bianya,"Vall de Bianya, La",Girona,350,421238N,022819E
295,0411X,Castello d'Empuries,Castelló d'Empúries,Girona,2,421329N,030535E
296,0413A,Maçanet de Cabrenys,Maçanet de Cabrenys,Girona,355,422313N,024520E
297,0421X,Espolla,Espolla,Girona,100,422324N,030022E
298,0429X,Figueres,Figueres,Girona,45,421533N,025737E
299,0433D,Cabo de Creus,Cadaqués,Girona,75,421909N,031857E
300,9585,La Molina,Alp,Girona,1703,421957N,015622E

In [51]:
for row in listado_estaciones.itertuples():
    
    print("El identificador de "+ row.Provincia +" "+ row.Nombre_est+ " es:"+ row.Identificador_est)

El identificador de A Coruña A Coruña es:1387
El identificador de A Coruña A Coruña Aeropuerto es:1387E
El identificador de A Coruña Carballo, Depuradora es:1390X
El identificador de A Coruña Cabo Vilan es:1393
El identificador de A Coruña Vimianzo es:1399
El identificador de A Coruña Fisterra es:1400
El identificador de A Coruña Mazaricos es:1406X
El identificador de A Coruña Sobrado es:1410X
El identificador de A Coruña Santiago de Compostela Aeropuerto es:1428
El identificador de A Coruña Noia es:1435C
El identificador de A Coruña Monte Iroite es:1437O
El identificador de A Coruña Boiro es:1442U
El identificador de A Coruña Padrón es:1473A
El identificador de A Coruña Santiago de Compostela es:1475X
El identificador de A Coruña Rois, Casas do Porto es:1476R
El identificador de Albacete Ossa de Montiel es:4007Y
El identificador de Albacete Villarrobledo es:4091Y
El identificador de Albacete Munera es:4096Y
El identificador de Albacete Yeste, Embalse Fuensanta es:7066Y
El identificador de Albacete Nerpio es:7067Y
El identificador de Albacete Yeste es:7072Y
El identificador de Albacete Hellín es:7096B
El identificador de Albacete Tobarra es:7103Y
El identificador de Albacete Albacete es:8178D
El identificador de Albacete Alcalá del Júcar es:8191Y
El identificador de Albacete Almansa es:8198Y
El identificador de Alacant/Alicante Orihuela es:7244X
El identificador de Alacant/Alicante Pinoso es:7247X
El identificador de Alacant/Alicante Rojales es:7261X
El identificador de Alacant/Alicante Villena es:8008Y
El identificador de Alacant/Alicante Novelda es:8013X
El identificador de Alacant/Alicante Elche/Elx es:8018X
El identificador de Alacant/Alicante Alicante/Alacant Aeropuerto es:8019
El identificador de Alacant/Alicante Alicante/Alacant es:8025
El identificador de Alacant/Alicante Benidorm es:8036Y
El identificador de Alacant/Alicante Jávea/ Xàbia es:8050X
El identificador de Alacant/Alicante Pego es:8057C
El identificador de Alacant/Alicante Alcoy/Alcoi es:8059C
El identificador de Almería Vélez Blanco es:5060X
El identificador de Almería Adra es:6277B
El identificador de Almería El Ejido es:6291B
El identificador de Almería Roquetas de Mar es:6293X
El identificador de Almería Abla es:6302A
El identificador de Almería Láujar de Andarax es:6307X
El identificador de Almería Almería Aeropuerto es:6325O
El identificador de Almería Cabo de Gata es:6329X
El identificador de Almería Garrucha, Puerto es:6340X
El identificador de Almería Albox es:6364X
El identificador de Almería Huercal Overa es:6367B
El identificador de Araba/Álava Aramaio es:1044X
El identificador de Araba/Álava Amurrio es:1060X
El identificador de Araba/Álava Lalastra es:9060X
El identificador de Araba/Álava Opakua es:9073X
El identificador de Araba/Álava Vitoria Gasteiz Aeropuerto es:9091R
El identificador de Araba/Álava Labastida es:9122I
El identificador de Araba/Álava Leza es:9145X
El identificador de Araba/Álava Campezo/Kanpezu es:9178X
El identificador de Asturias Cabrales es:1179B
El identificador de Asturias Llanes es:1183X
El identificador de Asturias Amieva, Panizales es:1186P
El identificador de Asturias Piloña es:1199X
El identificador de Asturias Colunga es:1203D
El identificador de Asturias Gijón, Campus es:1207U
El identificador de Asturias Cabo Peñas es:1210X
El identificador de Asturias Asturias Aeropuerto es:1212E
El identificador de Asturias Puerto de Pajares es:1221D
El identificador de Asturias Pola de Lena es:1223P
El identificador de Asturias Aller es:1226X
El identificador de Asturias Mieres es:1234P
El identificador de Asturias Oviedo es:1249X
El identificador de Asturias Tineo, Soto de la Barca es:1272B
El identificador de Asturias Pola de Somiedo es:1276F
El identificador de Asturias Salas es:1279X
El identificador de Asturias Cabo Busto es:1283U
El identificador de Asturias Degaña es:1302F
El identificador de Asturias Ibias, San Antolin es:1309C
El identificador de Asturias Villayón, Oneta es:1327A
El identificador de Asturias Castropol es:1331A
El identificador de Asturias Taramundi, Ouria es:1341B
El identificador de Asturias Puerto de Leitariegos es:1542
El identificador de Ávila Muñotello es:2430Y
El identificador de Ávila Ávila es:2444
El identificador de Ávila Gotarrendura es:2453E
El identificador de Ávila Arevalo es:2456B
El identificador de Ávila Rivilla de Barajas es:2512Y
El identificador de Ávila Navarredonda de Gredos es:2811A
El identificador de Ávila Barco de Avila es:2828Y
El identificador de Ávila Puerto El Pico es:3319D
El identificador de Ávila Cebreros es:3337U
El identificador de Ávila Candeleda es:3422D
El identificador de Badajoz Herrera del Duque es:4244X
El identificador de Badajoz Peraleda del Zaucejo es:4260
El identificador de Badajoz Castuera es:4325X
El identificador de Badajoz Navalvillar de Pela es:4340
El identificador de Badajoz Don Benito es:4358X
El identificador de Badajoz Llerena es:4386B
El identificador de Badajoz Villafranca de los Barros es:4395X
El identificador de Badajoz Mérida es:4410X
El identificador de Badajoz Zafra es:4427X
El identificador de Badajoz Almendralejo es:4436Y
El identificador de Badajoz Badajoz Aeropuerto es:4452
El identificador de Badajoz Alburquerque es:4464X
El identificador de Badajoz Puebla de Obando es:4468X
El identificador de Badajoz Badajoz es:4478X
El identificador de Badajoz Olivenza es:4486X
El identificador de Badajoz Alconchel es:4489X
El identificador de Badajoz Barcarrota es:4492E
El identificador de Badajoz Villanueva del Fresno es:4497X
El identificador de Badajoz Monesterio es:4499X
El identificador de Badajoz Fuente de Cantos es:4501X
El identificador de Badajoz Jerez de los Caballeros es:4511C
El identificador de Badajoz Fregenal de la Sierra es:4520X
El identificador de Badajoz Azuaga es:5473X
El identificador de Barcelona Pontons es:0061X
El identificador de Barcelona Vilafranca del Penedès es:0066X
El identificador de Barcelona Sitges es:0073X
El identificador de Barcelona Barcelona Aeropuerto es:0076
El identificador de Barcelona Berga es:0092X
El identificador de Barcelona Balsareny es:0106X
El identificador de Barcelona Prat de Lluçanès es:0114X
El identificador de Barcelona Moià es:0120X
El identificador de Barcelona Manresa es:0149X
El identificador de Barcelona Monistrol de Montserrat es:0158X
El identificador de Barcelona Igualada es:0171X
El identificador de Barcelona Corbera, Pic d'Agulles es:0194D
El identificador de Barcelona Barcelona es:0201D
El identificador de Barcelona Barcelona, Museo Marítimo es:0201X
El identificador de Barcelona Caldes de Montbui es:0222X
El identificador de Barcelona Sabadell Aeropuerto es:0229I
El identificador de Barcelona Vilassar de Dalt es:0244X
El identificador de Barcelona Arenys de Mar es:0252D
El identificador de Barcelona Santa Susana es:0255B
El identificador de Barcelona Fogars de Montclús es:0260X
El identificador de Barcelona Tona es:0341X
El identificador de Barcelona Sant Julià de Vilatorta es:0349
El identificador de Bizkaia Lekeitio es:1055B
El identificador de Bizkaia Forua es:1056K
El identificador de Bizkaia Machichaco es:1057B
El identificador de Bizkaia Punta Galea es:1059X
El identificador de Bizkaia Orozko es:1064L
El identificador de Bizkaia Abadiño es:1069Y
El identificador de Bizkaia Amorebieta--Etxano es:1074C
El identificador de Bizkaia Balmaseda es:1078C
El identificador de Bizkaia Güeñes es:1078I
El identificador de Bizkaia Bilbao Aeropuerto es:1082
El identificador de Bizkaia Sopuerta es:1083B
El identificador de Burgos Coruña del Conde es:2106B
El identificador de Burgos Aranda de Duero es:2117D
El identificador de Burgos Pedrosa del Príncipe es:2290Y
El identificador de Burgos Palacios de la Sierra es:2298
El identificador de Burgos Monterrubio de la Demanda es:2302N
El identificador de Burgos Villamayor de los Montes es:2311Y
El identificador de Burgos Burgos Aeropuerto es:2331X
El identificador de Burgos Santa Gadea de Alfoz es:9012E
El identificador de Burgos Sargentes de la Lora es:9027X
El identificador de Burgos Briviesca es:9031C
El identificador de Burgos Medina de Pomar es:9051
El identificador de Burgos Miranda de Ebro es:9069C
El identificador de Burgos Belorado es:9111
El identificador de Cáceres Navalvillar de Ibor es:3386A
El identificador de Cáceres Madrigal de la Vera es:3423I
El identificador de Cáceres Navalmoral de la Mata es:3434X
El identificador de Cáceres Garganta de la Olla es:3436D
El identificador de Cáceres Serradilla es:3448X
El identificador de Cáceres Jaraicejo es:3455X
El identificador de Cáceres Trujillo es:3463X
El identificador de Cáceres Cáceres es:3469A
El identificador de Cáceres Cañaveral es:3475X
El identificador de Cáceres Nuñomoral es:3494U
El identificador de Cáceres Guijo de Granadilla es:3503
El identificador de Cáceres Hervás es:3504X
El identificador de Cáceres Montehermoso es:3512X
El identificador de Cáceres Tornavacas es:3514B
El identificador de Cáceres Piornal es:3516X
El identificador de Cáceres Plasencia es:3519X
El identificador de Cáceres Coria es:3526X
El identificador de Cáceres Torrecilla de los Angeles es:3531X
El identificador de Cáceres Hoyos es:3536X
El identificador de Cáceres Zarza La Mayor es:3540X
El identificador de Cáceres Valverde del Fresno es:3547X
El identificador de Cáceres Aliseda es:3562X
El identificador de Cáceres Brozas es:3565X
El identificador de Cáceres Valencia de Alcántara es:3576X
El identificador de Cáceres Guadalupe es:4245X
El identificador de Cáceres Cañamero es:4339X
El identificador de Cáceres Zorita es:4347X
El identificador de Cáceres Alcuescar es:4411C
El identificador de Cádiz Chipiona es:5906X
El identificador de Cádiz Rota, Base Naval es:5910X
El identificador de Cádiz Grazalema es:5911A
El identificador de Cádiz Olvera es:5919X
El identificador de Cádiz El Bosque es:5941X
El identificador de Cádiz San José del Valle es:5950X
El identificador de Cádiz Jerez de la Frontera Aeropuerto es:5960
El identificador de Cádiz San Fernando es:5972X
El identificador de Cádiz Cádiz es:5973
El identificador de Cádiz Medina Sidonia es:5983X
El identificador de Cádiz Vejer de la Frontera es:5995B
El identificador de Cádiz Barbate es:5996B
El identificador de Cádiz Tarifa es:6001
El identificador de Cádiz Jimena de la Frontera es:6042I
El identificador de Cádiz San Roque es:6056X
El identificador de Cantabria Castro Urdiales es:1083L
El identificador de Cantabria Ramales de la Victoria es:1089U
El identificador de Cantabria Barcena de Cicero, Treto es:1096X
El identificador de Cantabria Soba, Alto Miera es:1102D
El identificador de Cantabria Santander Aeropuerto es:1109
El identificador de Cantabria Santander es:1111X
El identificador de Cantabria Villacarriedo es:1124E
El identificador de Cantabria Los Tojos, Bárcena Mayor es:1135C
El identificador de Cantabria San Felices de Buelna es:1152C
El identificador de Cantabria Torrelavega, Sierrapando es:1154H
El identificador de Cantabria San Vicente de la Barquera es:1159
El identificador de Cantabria Camaleño, Fuente De es:1167B
El identificador de Cantabria Cillórigo de Liébana, Tama es:1174I
El identificador de Cantabria Tresviso es:1176A
El identificador de Cantabria Santillana del Mar, Altamira es:1740
El identificador de Cantabria Reinosa es:9001D
El identificador de Cantabria Valderredible, Cubillo de Ebro es:9016X
El identificador de Cantabria Valderredible, Polientes es:9019B
El identificador de Castelló/Castellón Segorbe es:8439X
El identificador de Castelló/Castellón Montanejos es:8472A
El identificador de Castelló/Castellón Villafranca del Cid/Villafranca es:8489X
El identificador de Castelló/Castellón Atzeneta del Maestrat es:8492X
El identificador de Castelló/Castellón Castellón de la Plana, Almazora es:8500A
El identificador de Castelló/Castellón Torreblanca es:8503Y
El identificador de Castelló/Castellón La Pobla de Benifassà-Fredes es:8520X
El identificador de Castelló/Castellón Vinaròs es:8523X
El identificador de Castelló/Castellón Castellfort es:9563X
El identificador de Ceuta Ceuta es:5000C
El identificador de Ciudad Real Alcazar de San Juan es:4064Y
El identificador de Ciudad Real Tomelloso es:4103X
El identificador de Ciudad Real Ciudad Real es:4121
El identificador de Ciudad Real Villanueva de los Infantes es:4138Y
El identificador de Ciudad Real Valdepeñas es:4147X
El identificador de Ciudad Real Viso del Marqués es:4148
El identificador de Ciudad Real Abenójar es:4210Y
El identificador de Ciudad Real Puebla de Don Rodrigo es:4220X
El identificador de Ciudad Real Almadén es:4300Y
El identificador de Ciudad Real Puertollano es:5304Y
El identificador de Ciudad Real Fuencaliente es:5341C
El identificador de Córdoba Valsequillo es:4263X
El identificador de Córdoba Hinojosa del Duque es:4267X
El identificador de Córdoba Cardeña es:5346X
El identificador de Córdoba Montoro es:5361X
El identificador de Córdoba Villanueva de Córdoba es:5390Y
El identificador de Córdoba Córdoba es:5394X
El identificador de Córdoba Córdoba Aeropuerto es:5402
El identificador de Córdoba Priego de Cordoba es:5412X
El identificador de Córdoba Doña Mencía es:5427X
El identificador de Córdoba Córdoba, Prágdena es:5429X
El identificador de Córdoba Espiel es:5459X
El identificador de Córdoba Fuente Palmera es:5470
El identificador de Córdoba Benamejí es:5598X
El identificador de Córdoba Aguilar de la Frontera es:5624X
El identificador de Córdoba La Rambla es:5625X
El identificador de Cuenca Beteta es:3040Y
El identificador de Cuenca Cañizares es:3044X
El identificador de Cuenca Tarancón es:3094B
El identificador de Cuenca Alcázar del Rey es:4051Y
El identificador de Cuenca Abia de Obispalia es:4070Y
El identificador de Cuenca Villares del Saz es:4075Y
El identificador de Cuenca Alberca de Zancara es:4089A
El identificador de Cuenca Osa de la Vega es:4093Y
El identificador de Cuenca Belmonte es:4095Y
El identificador de Cuenca Cuenca es:8096
El identificador de Cuenca Motilla del Palancar es:8155Y
El identificador de Cuenca Salvacañete es:8210Y
El identificador de Cuenca Mira es:8245Y
El identificador de Gipuzkoa Irún es:1012P
El identificador de Gipuzkoa San Sebastián Aeropuerto es:1014A
El identificador de Gipuzkoa Renteria es:1021X
El identificador de Gipuzkoa Beasain es:1025X
El identificador de Gipuzkoa Ordizia es:1026X
El identificador de Gipuzkoa Zarautz es:1036A
El identificador de Gipuzkoa Legazpia es:1037X
El identificador de Gipuzkoa Zumarraga es:1037Y
El identificador de Gipuzkoa Azpeitia es:1038X
El identificador de Gipuzkoa Zumaia es:1041A
El identificador de Gipuzkoa Aretxabaleta es:1048X
El identificador de Gipuzkoa Elgeta es:1049N
El identificador de Gipuzkoa Elgoibar es:1050J
El identificador de Gipuzkoa Mutriku es:1052A
El identificador de Girona Blanes es:0281Y
El identificador de Girona Castell, Platja d`Aro es:0284X
El identificador de Girona Sant Pau de Segúries es:0312X
El identificador de Girona Planoles es:0320I
El identificador de Girona Ripoll es:0324A
El identificador de Girona Les Planes d'Hostoles es:0360X
El identificador de Girona Sant Hilari es:0363X
El identificador de Girona Girona Aeropuerto es:0367
El identificador de Girona Girona es:0370E
El identificador de Girona Porqueres es:0372C
El identificador de Girona L'Estartit es:0385X
El identificador de Girona La Vall de Bianya es:0394X
El identificador de Girona Castello d'Empuries es:0411X
El identificador de Girona Maçanet de Cabrenys es:0413A
El identificador de Girona Espolla es:0421X
El identificador de Girona Figueres es:0429X
El identificador de Girona Cabo de Creus es:0433D
El identificador de Girona La Molina es:9585
El identificador de Granada Baza es:5047E
El identificador de Granada Víznar es:5515D
El identificador de Granada Granada-Cartuja es:5515X
El identificador de Granada Granada Aeropuerto es:5530E
El identificador de Granada Loja es:5582A
El identificador de Granada Lanjarón es:6258X
El identificador de Granada Salobreña es:6267X
El identificador de Granada Motril es:6268X
El identificador de Granada Motril, Puerto es:6268Y
El identificador de Granada Castell del Ferro es:6272X
El identificador de Granada Válor es:6281X
El identificador de Guadalajara Molina de Aragón es:3013
El identificador de Guadalajara Zaorejas es:3021Y
El identificador de Guadalajara Pastrana es:3085Y
El identificador de Guadalajara Retiendas es:3103
El identificador de Guadalajara Sigüenza es:3130C
El identificador de Guadalajara Mandayona es:3140Y
El identificador de Guadalajara Campisábalos es:3158D
El identificador de Guadalajara Guadalajara es:3168D
El identificador de Guadalajara Brihuega es:3209Y
El identificador de Guadalajara El Pedregal es:9377Y
El identificador de Huelva Aroche es:4527X
El identificador de Huelva El Granado es:4541X
El identificador de Huelva Ayamonte es:4549Y
El identificador de Huelva Cartaya es:4554X
El identificador de Huelva Alajar es:4560Y
El identificador de Huelva Valverde del Camino es:4575X
El identificador de Huelva El Cerro de Andévalo es:4584X
El identificador de Huelva Alosno, Tharsis es:4589X
El identificador de Huelva El Campillo es:4608X
El identificador de Huelva Villarrasa es:4622X
El identificador de Huelva Huelva, Ronda Este es:4642E
El identificador de Huelva Cala es:5769X
El identificador de Huelva Almonte es:5858X
El identificador de Huelva Moguer, El Arenosillo es:5860E
El identificador de Huesca Canfranc es:9198X
El identificador de Huesca Jaca es:9201K
El identificador de Huesca Valle de Hecho, Hecho es:9207
El identificador de Huesca Aragüés del Puerto es:9208E
El identificador de Huesca Bailo es:9211F
El identificador de Huesca Biescas es:9453X
El identificador de Huesca Sabiñánigo es:9460X
El identificador de Huesca Almudévar es:9491X
El identificador de Huesca Sopeira es:9751
El identificador de Huesca Benabarre es:9756X
El identificador de Huesca Bielsa es:9784P
El identificador de Huesca Ainsa es:9808X
El identificador de Huesca Torla es:9814A
El identificador de Huesca Benasque es:9838B
El identificador de Huesca Seira es:9843A
El identificador de Huesca Capella es:9855E
El identificador de Huesca Barbastro es:9866C
El identificador de Huesca Sariñena, Depósito agua es:9894Y
El identificador de Huesca Huesca Aeropuerto es:9898
El identificador de Huesca Huesca es:9901X
El identificador de Huesca Lanaja es:9908X
El identificador de Huesca Ballobar es:9911X
El identificador de Huesca Tamarite de Litera es:9918Y
El identificador de Huesca Fraga es:9924X
El identificador de Illes Balears Escorca, Lluc es:B013X
El identificador de Illes Balears Banyalbufar es:B087X
El identificador de Illes Balears Calvià, Es Capdellà es:B158X
El identificador de Illes Balears Palma de Mallorca, Puerto es:B228
El identificador de Illes Balears Palma de Mallorca, Universidad es:B236C
El identificador de Illes Balears Sierra de Alfabia, Bunyola es:B248
El identificador de Illes Balears Marratxí es:B275C
El identificador de Illes Balears Palma de Mallorca, Aeropuerto es:B278
El identificador de Illes Balears Palma de Mallorca, Es Pil Larí es:B278C
El identificador de Illes Balears Llucmajor, Cap Blanc es:B301
El identificador de Illes Balears Llucmajor es:B334X
El identificador de Illes Balears Porreres es:B346X
El identificador de Illes Balears Campos, Can Sion es:B362X
El identificador de Illes Balears Campos, Salines Llevant es:B373X
El identificador de Illes Balears Santanyí es:B410B
El identificador de Illes Balears Portocolom es:B434X
El identificador de Illes Balears Son Servera es:B496X
El identificador de Illes Balears Artà es:B526X
El identificador de Illes Balears Capdepera es:B569X
El identificador de Illes Balears Artà-Colònia de Sant Pere es:B603X
El identificador de Illes Balears Muro, S'Albufera es:B605X
El identificador de Illes Balears Manacor es:B614E
El identificador de Illes Balears Sineu es:B644B
El identificador de Illes Balears Santa María del Camí es:B656A
El identificador de Illes Balears Binissalem es:B662X
El identificador de Illes Balears Escorca, Son Torrella es:B684A

In [52]:
for row in listado_estaciones.itertuples():
    print(row)

Pandas(Index=0, Identificador_est='1387', Nombre_est='A Coruña', Municipio='Coruña, A', Provincia='A Coruña', Altura='58', Longitud='432157N', Latitud='082517W')
Pandas(Index=1, Identificador_est='1387E', Nombre_est='A Coruña Aeropuerto', Municipio='Culleredo', Provincia='A Coruña', Altura='98', Longitud='431825N', Latitud='082219W')
Pandas(Index=2, Identificador_est='1390X', Nombre_est='Carballo, Depuradora', Municipio='Carballo', Provincia='A Coruña', Altura='98', Longitud='431213N', Latitud='084239W')
Pandas(Index=3, Identificador_est='1393', Nombre_est='Cabo Vilan', Municipio='Camariñas', Provincia='A Coruña', Altura='50', Longitud='430938N', Latitud='091239W')
Pandas(Index=4, Identificador_est='1399', Nombre_est='Vimianzo', Municipio='Vimianzo', Provincia='A Coruña', Altura='287', Longitud='430327N', Latitud='090249W')
Pandas(Index=5, Identificador_est='1400', Nombre_est='Fisterra', Municipio='Fisterra', Provincia='A Coruña', Altura='230', Longitud='425529N', Latitud='091729W')
Pandas(Index=6, Identificador_est='1406X', Nombre_est='Mazaricos', Municipio='Mazaricos', Provincia='A Coruña', Altura='340', Longitud='425607N', Latitud='085937W')
Pandas(Index=7, Identificador_est='1410X', Nombre_est='Sobrado', Municipio='Sobrado', Provincia='A Coruña', Altura='500', Longitud='430216N', Latitud='080120W')
Pandas(Index=8, Identificador_est='1428', Nombre_est='Santiago de Compostela Aeropuerto', Municipio='Pino, O', Provincia='A Coruña', Altura='370', Longitud='425317N', Latitud='082438W')
Pandas(Index=9, Identificador_est='1435C', Nombre_est='Noia', Municipio='Noia', Provincia='A Coruña', Altura='128', Longitud='424801N', Latitud='085234W')
Pandas(Index=10, Identificador_est='1437O', Nombre_est='Monte Iroite', Municipio='Porto do Son', Provincia='A Coruña', Altura='685', Longitud='424314N', Latitud='085524W')
Pandas(Index=11, Identificador_est='1442U', Nombre_est='Boiro', Municipio='Boiro', Provincia='A Coruña', Altura='10', Longitud='423838N', Latitud='085332W')
Pandas(Index=12, Identificador_est='1473A', Nombre_est='Padrón', Municipio='Padrón', Provincia='A Coruña', Altura='100', Longitud='424418N', Latitud='083738W')
Pandas(Index=13, Identificador_est='1475X', Nombre_est='Santiago de Compostela', Municipio='Santiago de Compostela', Provincia='A Coruña', Altura='240', Longitud='425234N', Latitud='083321W')
Pandas(Index=14, Identificador_est='1476R', Nombre_est='Rois, Casas do Porto', Municipio='Rois', Provincia='A Coruña', Altura='210', Longitud='424459N', Latitud='084253W')
Pandas(Index=15, Identificador_est='4007Y', Nombre_est='Ossa de Montiel', Municipio='Ossa de Montiel', Provincia='Albacete', Altura='905', Longitud='385757N', Latitud='024442W')
Pandas(Index=16, Identificador_est='4091Y', Nombre_est='Villarrobledo', Municipio='Villarrobledo', Provincia='Albacete', Altura='718', Longitud='391543N', Latitud='023533W')
Pandas(Index=17, Identificador_est='4096Y', Nombre_est='Munera', Municipio='Munera', Provincia='Albacete', Altura='918', Longitud='390100N', Latitud='022920W')
Pandas(Index=18, Identificador_est='7066Y', Nombre_est='Yeste, Embalse Fuensanta', Municipio='Yeste', Provincia='Albacete', Altura='680', Longitud='382335N', Latitud='021308W')
Pandas(Index=19, Identificador_est='7067Y', Nombre_est='Nerpio', Municipio='Nerpio', Provincia='Albacete', Altura='1485', Longitud='380518N', Latitud='022447W')
Pandas(Index=20, Identificador_est='7072Y', Nombre_est='Yeste', Municipio='Yeste', Provincia='Albacete', Altura='960', Longitud='381742N', Latitud='021738W')
Pandas(Index=21, Identificador_est='7096B', Nombre_est='Hellín', Municipio='Hellín', Provincia='Albacete', Altura='605', Longitud='383231N', Latitud='014211W')
Pandas(Index=22, Identificador_est='7103Y', Nombre_est='Tobarra', Municipio='Tobarra', Provincia='Albacete', Altura='615', Longitud='383517N', Latitud='014122W')
Pandas(Index=23, Identificador_est='8178D', Nombre_est='Albacete', Municipio='Albacete', Provincia='Albacete', Altura='674', Longitud='390020N', Latitud='015144W')
Pandas(Index=24, Identificador_est='8191Y', Nombre_est='Alcalá del Júcar', Municipio='Alcalá del Júcar', Provincia='Albacete', Altura='680', Longitud='391155N', Latitud='012608W')
Pandas(Index=25, Identificador_est='8198Y', Nombre_est='Almansa', Municipio='Almansa', Provincia='Albacete', Altura='710', Longitud='385102N', Latitud='010347W')
Pandas(Index=26, Identificador_est='7244X', Nombre_est='Orihuela', Municipio='Orihuela', Provincia='Alacant/Alicante', Altura='26', Longitud='380404N', Latitud='005853W')
Pandas(Index=27, Identificador_est='7247X', Nombre_est='Pinoso', Municipio='Pinós, el/Pinoso', Provincia='Alacant/Alicante', Altura='575', Longitud='382359N', Latitud='010217W')
Pandas(Index=28, Identificador_est='7261X', Nombre_est='Rojales', Municipio='Rojales', Provincia='Alacant/Alicante', Altura='31', Longitud='380517N', Latitud='004255W')
Pandas(Index=29, Identificador_est='8008Y', Nombre_est='Villena', Municipio='Villena', Provincia='Alacant/Alicante', Altura='486', Longitud='383437N', Latitud='005156W')
Pandas(Index=30, Identificador_est='8013X', Nombre_est='Novelda', Municipio='Novelda', Provincia='Alacant/Alicante', Altura='230', Longitud='382312N', Latitud='004528W')
Pandas(Index=31, Identificador_est='8018X', Nombre_est='Elche/Elx', Municipio='Elche/Elx', Provincia='Alacant/Alicante', Altura='110', Longitud='381715N', Latitud='004050W')
Pandas(Index=32, Identificador_est='8019', Nombre_est='Alicante/Alacant Aeropuerto', Municipio='Elche/Elx', Provincia='Alacant/Alicante', Altura='43', Longitud='381658N', Latitud='003415W')
Pandas(Index=33, Identificador_est='8025', Nombre_est='Alicante/Alacant', Municipio='Alicante/Alacant', Provincia='Alacant/Alicante', Altura='81', Longitud='382221N', Latitud='002939W')
Pandas(Index=34, Identificador_est='8036Y', Nombre_est='Benidorm', Municipio='Benidorm', Provincia='Alacant/Alicante', Altura='70', Longitud='383306N', Latitud='000800W')
Pandas(Index=35, Identificador_est='8050X', Nombre_est='Jávea/ Xàbia', Municipio='Jávea/Xàbia', Provincia='Alacant/Alicante', Altura='15', Longitud='384701N', Latitud='001004E')
Pandas(Index=36, Identificador_est='8057C', Nombre_est='Pego', Municipio='Pego', Provincia='Alacant/Alicante', Altura='60', Longitud='385048N', Latitud='000706W')
Pandas(Index=37, Identificador_est='8059C', Nombre_est='Alcoy/Alcoi', Municipio='Alcoy/Alcoi', Provincia='Alacant/Alicante', Altura='530', Longitud='384239N', Latitud='002736W')
Pandas(Index=38, Identificador_est='5060X', Nombre_est='Vélez Blanco', Municipio='Vélez-Blanco', Provincia='Almería', Altura='1190', Longitud='375139N', Latitud='021341W')
Pandas(Index=39, Identificador_est='6277B', Nombre_est='Adra', Municipio='Adra', Provincia='Almería', Altura='8', Longitud='364450N', Latitud='030114W')
Pandas(Index=40, Identificador_est='6291B', Nombre_est='El Ejido', Municipio='Ejido, El', Provincia='Almería', Altura='98', Longitud='364629N', Latitud='024847W')
Pandas(Index=41, Identificador_est='6293X', Nombre_est='Roquetas de Mar', Municipio='Ejido, El', Provincia='Almería', Altura='3', Longitud='364113N', Latitud='024206W')
Pandas(Index=42, Identificador_est='6302A', Nombre_est='Abla', Municipio='Abla', Provincia='Almería', Altura='885', Longitud='370829N', Latitud='024647W')
Pandas(Index=43, Identificador_est='6307X', Nombre_est='Láujar de Andarax', Municipio='Láujar de Andarax', Provincia='Almería', Altura='1518', Longitud='370159N', Latitud='025445W')
Pandas(Index=44, Identificador_est='6325O', Nombre_est='Almería Aeropuerto', Municipio='Almería', Provincia='Almería', Altura='21', Longitud='365047N', Latitud='022125W')
Pandas(Index=45, Identificador_est='6329X', Nombre_est='Cabo de Gata', Municipio='Níjar', Provincia='Almería', Altura='52', Longitud='364319N', Latitud='021135W')
Pandas(Index=46, Identificador_est='6340X', Nombre_est='Garrucha, Puerto', Municipio='Garrucha', Provincia='Almería', Altura='6', Longitud='371044N', Latitud='014900W')
Pandas(Index=47, Identificador_est='6364X', Nombre_est='Albox', Municipio='Albox', Provincia='Almería', Altura='508', Longitud='372424N', Latitud='020905W')
Pandas(Index=48, Identificador_est='6367B', Nombre_est='Huercal Overa', Municipio='Huércal-Overa', Provincia='Almería', Altura='300', Longitud='372326N', Latitud='015637W')
Pandas(Index=49, Identificador_est='1044X', Nombre_est='Aramaio', Municipio='Aramaio', Provincia='Araba/Álava', Altura='617', Longitud='430328N', Latitud='023522W')
Pandas(Index=50, Identificador_est='1060X', Nombre_est='Amurrio', Municipio='Amurrio', Provincia='Araba/Álava', Altura='240', Longitud='430301N', Latitud='030020W')
Pandas(Index=51, Identificador_est='9060X', Nombre_est='Lalastra', Municipio='Valdegovía/Gaubea', Provincia='Araba/Álava', Altura='910', Longitud='425231N', Latitud='031354W')
Pandas(Index=52, Identificador_est='9073X', Nombre_est='Opakua', Municipio='Salvatierra/Agurain', Provincia='Araba/Álava', Altura='660', Longitud='424947N', Latitud='022135W')
Pandas(Index=53, Identificador_est='9091R', Nombre_est='Vitoria Gasteiz Aeropuerto', Municipio='Vitoria-Gasteiz', Provincia='Araba/Álava', Altura='513', Longitud='425219N', Latitud='024400W')
Pandas(Index=54, Identificador_est='9122I', Nombre_est='Labastida', Municipio='Labastida/Bastida', Provincia='Araba/Álava', Altura='610', Longitud='423609N', Latitud='024629W')
Pandas(Index=55, Identificador_est='9145X', Nombre_est='Leza', Municipio='Leza', Provincia='Araba/Álava', Altura='575', Longitud='423402N', Latitud='023758W')
Pandas(Index=56, Identificador_est='9178X', Nombre_est='Campezo/Kanpezu', Municipio='Campezo/Kanpezu', Provincia='Araba/Álava', Altura='570', Longitud='424014N', Latitud='022046W')
Pandas(Index=57, Identificador_est='1179B', Nombre_est='Cabrales', Municipio='Cabrales', Provincia='Asturias', Altura='458', Longitud='431840N', Latitud='045110W')
Pandas(Index=58, Identificador_est='1183X', Nombre_est='Llanes', Municipio='Llanes', Provincia='Asturias', Altura='10', Longitud='432513N', Latitud='044453W')
Pandas(Index=59, Identificador_est='1186P', Nombre_est='Amieva, Panizales', Municipio='Amieva', Provincia='Asturias', Altura='370', Longitud='431600N', Latitud='050709W')
Pandas(Index=60, Identificador_est='1199X', Nombre_est='Piloña', Municipio='Piloña', Provincia='Asturias', Altura='280', Longitud='432240N', Latitud='052348W')
Pandas(Index=61, Identificador_est='1203D', Nombre_est='Colunga', Municipio='Colunga', Provincia='Asturias', Altura='30', Longitud='432933N', Latitud='051450W')
Pandas(Index=62, Identificador_est='1207U', Nombre_est='Gijón, Campus', Municipio='Gijón', Provincia='Asturias', Altura='26', Longitud='433123N', Latitud='053716W')
Pandas(Index=63, Identificador_est='1210X', Nombre_est='Cabo Peñas', Municipio='Gozón', Provincia='Asturias', Altura='100', Longitud='433921N', Latitud='055055W')
Pandas(Index=64, Identificador_est='1212E', Nombre_est='Asturias Aeropuerto', Municipio='Castrillón', Provincia='Asturias', Altura='127', Longitud='433401N', Latitud='060239W')
Pandas(Index=65, Identificador_est='1221D', Nombre_est='Puerto de Pajares', Municipio='Lena', Provincia='Asturias', Altura='1480', Longitud='425843N', Latitud='054635W')
Pandas(Index=66, Identificador_est='1223P', Nombre_est='Pola de Lena', Municipio='Lena', Provincia='Asturias', Altura='370', Longitud='430758N', Latitud='054922W')
Pandas(Index=67, Identificador_est='1226X', Nombre_est='Aller', Municipio='Aller', Provincia='Asturias', Altura='750', Longitud='430543N', Latitud='052837W')
Pandas(Index=68, Identificador_est='1234P', Nombre_est='Mieres', Municipio='Mieres', Provincia='Asturias', Altura='170', Longitud='431630N', Latitud='054909W')
Pandas(Index=69, Identificador_est='1249X', Nombre_est='Oviedo', Municipio='Oviedo', Provincia='Asturias', Altura='336', Longitud='432112N', Latitud='055227W')
Pandas(Index=70, Identificador_est='1272B', Nombre_est='Tineo, Soto de la Barca', Municipio='Tineo', Provincia='Asturias', Altura='280', Longitud='431725N', Latitud='062312W')
Pandas(Index=71, Identificador_est='1276F', Nombre_est='Pola de Somiedo', Municipio='Somiedo', Provincia='Asturias', Altura='670', Longitud='430600N', Latitud='061525W')
Pandas(Index=72, Identificador_est='1279X', Nombre_est='Salas', Municipio='Salas', Provincia='Asturias', Altura='240', Longitud='432530N', Latitud='061351W')
Pandas(Index=73, Identificador_est='1283U', Nombre_est='Cabo Busto', Municipio='Valdés', Provincia='Asturias', Altura='60', Longitud='433409N', Latitud='062812W')
Pandas(Index=74, Identificador_est='1302F', Nombre_est='Degaña', Municipio='Degaña', Provincia='Asturias', Altura='1310', Longitud='425719N', Latitud='062821W')
Pandas(Index=75, Identificador_est='1309C', Nombre_est='Ibias, San Antolin', Municipio='Ibias', Provincia='Asturias', Altura='780', Longitud='430139N', Latitud='065306W')
Pandas(Index=76, Identificador_est='1327A', Nombre_est='Villayón, Oneta', Municipio='Villayón', Provincia='Asturias', Altura='410', Longitud='432756N', Latitud='064024W')
Pandas(Index=77, Identificador_est='1331A', Nombre_est='Castropol', Municipio='Castropol', Provincia='Asturias', Altura='40', Longitud='433129N', Latitud='070153W')
Pandas(Index=78, Identificador_est='1341B', Nombre_est='Taramundi, Ouria', Municipio='Taramundi', Provincia='Asturias', Altura='340', Longitud='432456N', Latitud='070340W')
Pandas(Index=79, Identificador_est='1542', Nombre_est='Puerto de Leitariegos', Municipio='Cangas del Narcea', Provincia='Asturias', Altura='1530', Longitud='425939N', Latitud='062451W')
Pandas(Index=80, Identificador_est='2430Y', Nombre_est='Muñotello', Municipio='Muñotello', Provincia='Ávila', Altura='1178', Longitud='403236N', Latitud='050239W')
Pandas(Index=81, Identificador_est='2444', Nombre_est='Ávila', Municipio='Ávila', Provincia='Ávila', Altura='1130', Longitud='403933N', Latitud='044048W')
Pandas(Index=82, Identificador_est='2453E', Nombre_est='Gotarrendura', Municipio='Gotarrendura', Provincia='Ávila', Altura='920', Longitud='404944N', Latitud='044431W')
Pandas(Index=83, Identificador_est='2456B', Nombre_est='Arevalo', Municipio='Arévalo', Provincia='Ávila', Altura='820', Longitud='410417N', Latitud='044348W')
Pandas(Index=84, Identificador_est='2512Y', Nombre_est='Rivilla de Barajas', Municipio='Rivilla de Barajas', Provincia='Ávila', Altura='925', Longitud='405256N', Latitud='050107W')
Pandas(Index=85, Identificador_est='2811A', Nombre_est='Navarredonda de Gredos', Municipio='Navarredonda de Gredos', Provincia='Ávila', Altura='1525', Longitud='402102N', Latitud='050835W')
Pandas(Index=86, Identificador_est='2828Y', Nombre_est='Barco de Avila', Municipio='Barco de Ávila, El', Provincia='Ávila', Altura='1012', Longitud='402119N', Latitud='053109W')
Pandas(Index=87, Identificador_est='3319D', Nombre_est='Puerto El Pico', Municipio='Villarejo del Valle', Provincia='Ávila', Altura='1285', Longitud='402023N', Latitud='050046W')
Pandas(Index=88, Identificador_est='3337U', Nombre_est='Cebreros', Municipio='Cebreros', Provincia='Ávila', Altura='850', Longitud='402803N', Latitud='042721W')
Pandas(Index=89, Identificador_est='3422D', Nombre_est='Candeleda', Municipio='Candeleda', Provincia='Ávila', Altura='350', Longitud='400821N', Latitud='051841W')
Pandas(Index=90, Identificador_est='4244X', Nombre_est='Herrera del Duque', Municipio='Herrera del Duque', Provincia='Badajoz', Altura='447', Longitud='391010N', Latitud='050344W')
Pandas(Index=91, Identificador_est='4260', Nombre_est='Peraleda del Zaucejo', Municipio='Peraleda del Zaucejo', Provincia='Badajoz', Altura='542', Longitud='382847N', Latitud='053439W')
Pandas(Index=92, Identificador_est='4325X', Nombre_est='Castuera', Municipio='Castuera', Provincia='Badajoz', Altura='502', Longitud='384255N', Latitud='053248W')
Pandas(Index=93, Identificador_est='4340', Nombre_est='Navalvillar de Pela', Municipio='Navalvillar de Pela', Provincia='Badajoz', Altura='313', Longitud='390612N', Latitud='052741W')
Pandas(Index=94, Identificador_est='4358X', Nombre_est='Don Benito', Municipio='Don Benito', Provincia='Badajoz', Altura='273', Longitud='385720N', Latitud='055250W')
Pandas(Index=95, Identificador_est='4386B', Nombre_est='Llerena', Municipio='Llerena', Provincia='Badajoz', Altura='655', Longitud='381354N', Latitud='060101W')
Pandas(Index=96, Identificador_est='4395X', Nombre_est='Villafranca de los Barros', Municipio='Villafranca de los Barros', Provincia='Badajoz', Altura='430', Longitud='383306N', Latitud='061824W')
Pandas(Index=97, Identificador_est='4410X', Nombre_est='Mérida', Municipio='Mérida', Provincia='Badajoz', Altura='228', Longitud='385457N', Latitud='062308W')
Pandas(Index=98, Identificador_est='4427X', Nombre_est='Zafra', Municipio='Zafra', Provincia='Badajoz', Altura='433', Longitud='382533N', Latitud='062612W')
Pandas(Index=99, Identificador_est='4436Y', Nombre_est='Almendralejo', Municipio='Almendralejo', Provincia='Badajoz', Altura='371', Longitud='384120N', Latitud='062140W')
Pandas(Index=100, Identificador_est='4452', Nombre_est='Badajoz Aeropuerto', Municipio='Badajoz', Provincia='Badajoz', Altura='185', Longitud='385300N', Latitud='064850W')
Pandas(Index=101, Identificador_est='4464X', Nombre_est='Alburquerque', Municipio='Alburquerque', Provincia='Badajoz', Altura='283', Longitud='391055N', Latitud='065943W')
Pandas(Index=102, Identificador_est='4468X', Nombre_est='Puebla de Obando', Municipio='Puebla de Obando', Provincia='Badajoz', Altura='392', Longitud='391036N', Latitud='063603W')
Pandas(Index=103, Identificador_est='4478X', Nombre_est='Badajoz', Municipio='Badajoz', Provincia='Badajoz', Altura='175', Longitud='385315N', Latitud='070029W')
Pandas(Index=104, Identificador_est='4486X', Nombre_est='Olivenza', Municipio='Olivenza', Provincia='Badajoz', Altura='275', Longitud='384151N', Latitud='070504W')
Pandas(Index=105, Identificador_est='4489X', Nombre_est='Alconchel', Municipio='Alconchel', Provincia='Badajoz', Altura='170', Longitud='382905N', Latitud='071655W')
Pandas(Index=106, Identificador_est='4492E', Nombre_est='Barcarrota', Municipio='Barcarrota', Provincia='Badajoz', Altura='387', Longitud='382835N', Latitud='065522W')
Pandas(Index=107, Identificador_est='4497X', Nombre_est='Villanueva del Fresno', Municipio='Villanueva del Fresno', Provincia='Badajoz', Altura='247', Longitud='382220N', Latitud='070929W')
Pandas(Index=108, Identificador_est='4499X', Nombre_est='Monesterio', Municipio='Monesterio', Provincia='Badajoz', Altura='771', Longitud='380453N', Latitud='061619W')
Pandas(Index=109, Identificador_est='4501X', Nombre_est='Fuente de Cantos', Municipio='Fuente de Cantos', Provincia='Badajoz', Altura='602', Longitud='381232N', Latitud='061841W')
Pandas(Index=110, Identificador_est='4511C', Nombre_est='Jerez de los Caballeros', Municipio='Jerez de los Caballeros', Provincia='Badajoz', Altura='381', Longitud='381755N', Latitud='064554W')
Pandas(Index=111, Identificador_est='4520X', Nombre_est='Fregenal de la Sierra', Municipio='Fregenal de la Sierra', Provincia='Badajoz', Altura='586', Longitud='381042N', Latitud='063942W')
Pandas(Index=112, Identificador_est='5473X', Nombre_est='Azuaga', Municipio='Azuaga', Provincia='Badajoz', Altura='581', Longitud='381604N', Latitud='054110W')
Pandas(Index=113, Identificador_est='0061X', Nombre_est='Pontons', Municipio='Pontons', Provincia='Barcelona', Altura='632', Longitud='412501N', Latitud='013109E')
Pandas(Index=114, Identificador_est='0066X', Nombre_est='Vilafranca del Penedès', Municipio='Vilafranca del Penedès', Provincia='Barcelona', Altura='177', Longitud='411949N', Latitud='014037E')
Pandas(Index=115, Identificador_est='0073X', Nombre_est='Sitges', Municipio='Sitges', Provincia='Barcelona', Altura='58', Longitud='411438N', Latitud='015109E')
Pandas(Index=116, Identificador_est='0076', Nombre_est='Barcelona Aeropuerto', Municipio='Prat de Llobregat, El', Provincia='Barcelona', Altura='4', Longitud='411734N', Latitud='020412E')

In [53]:
provincias = listado_estaciones["Provincia"].unique()
provincias = pd.DataFrame(list(provincias))
provincias

                         0
0                 A Coruña
1                 Albacete
2         Alacant/Alicante
3                  Almería
4              Araba/Álava
5                 Asturias
6                    Ávila
7                  Badajoz
8                Barcelona
9                  Bizkaia
10                  Burgos
11                 Cáceres
12                   Cádiz
13               Cantabria
14      Castelló/Castellón
15                   Ceuta
16             Ciudad Real
17                 Córdoba
18                  Cuenca
19                Gipuzkoa
20                  Girona
21                 Granada
22             Guadalajara
23                  Huelva
24                  Huesca
25           Illes Balears
26                    Jaén
27                La Rioja
28              Las Palmas
29                    León
30                  Lleida
31                    Lugo
32                  Madrid
33                  Málaga
34                 Melilla
35                  Murcia
36                 Navarra
37                 Ourense
38                Palencia
39              Pontevedra
40               Salamanca
41                 Segovia
42                 Sevilla
43                   Soria
44  Santa Cruz de Tenerife
45               Tarragona
46                  Teruel
47                  Toledo
48       València/Valencia
49              Valladolid
50                  Zamora
51                Zaragoza

In [54]:
listado_estaciones.sort_values("Provincia", inplace = True)
listado_estaciones

,Identificador_est,Nombre_est,Municipio,Provincia,Altura,Longitud,Latitud
0,1387,A Coruña,"Coruña, A",A Coruña,58,432157N,082517W
835,1354C,Ferrol,Ferrol,A Coruña,4,432835N,081533W
798,1351,Estaca de Bares,Mañón,A Coruña,80,434710N,074105W
14,1476R,"Rois, Casas do Porto",Rois,A Coruña,210,424459N,084253W
13,1475X,Santiago de Compostela,Santiago de Compostela,A Coruña,240,425234N,083321W
...,...,...,...,...,...,...,...
87,3319D,Puerto El Pico,Villarejo del Valle,Ávila,1285,402023N,050046W
803,3391,Sotillo de la Adrada,Sotillo de la Adrada,Ávila,630,401719N,043527W
89,3422D,Candeleda,Candeleda,Ávila,350,400821N,051841W
84,2512Y,Rivilla de Barajas,Rivilla de Barajas,Ávila,925,405256N,050107W
88,3337U,Cebreros,Cebreros,Ávila,850,402803N,042721W

The next few cells do not work, as I was just trying to get the "Identificador de estación" without success

In [55]:
for provincia in listado_estaciones["Provincia"]:
    
    for i in range(len(provincias)):
    
        if provincia == provincias.iloc[i,0]:

            print(listado_estaciones["Identificador_est"])

0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object

0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U

Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object

0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U

Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object

0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object

0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U

Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U

Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U

Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X

Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object

0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U

Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object
0       1387
835    1354C
798     1351
14     1476R
13     1475X
       ...
87     3319D
803     3391
89     3422D
84     2512Y
88     3337U
Name: Identificador_est, Length: 848, dtype: object

In [56]:
for index, fila in listado_estaciones.iterrows():
    
    print(fila["Provincia"], fila["Identificador_est"])

A Coruña 1387
A Coruña 1354C
A Coruña 1351
A Coruña 1476R
A Coruña 1475X
A Coruña 1473A
A Coruña 1442U
A Coruña 1437O
A Coruña 1435C
A Coruña 1387D
A Coruña 1410X
A Coruña 1428
A Coruña 1387E
A Coruña 1393
A Coruña 1390X
A Coruña 1406X
A Coruña 1400
A Coruña 1399
Alacant/Alicante 8050X
Alacant/Alicante 8059C
Alacant/Alicante 8057C
Alacant/Alicante 8036Y
Alacant/Alicante 8025
Alacant/Alicante 8018X
Alacant/Alicante 8013X
Alacant/Alicante 8008Y
Alacant/Alicante 7261X
Alacant/Alicante 8019
Alacant/Alicante 7244X
Alacant/Alicante 7247X
Albacete 4091Y
Albacete 4096Y
Albacete 8175
Albacete 7066Y
Albacete 7067Y
Albacete 4007Y
Albacete 7096B
Albacete 7103Y
Albacete 8198Y
Albacete 8177A
Albacete 8191Y
Albacete 8178D
Albacete 7072Y
Almería 6332X
Almería 6381
Almería 6367B
Almería 6364X
Almería 6329X
Almería 6325O
Almería 6307X
Almería 6302A
Almería 6291B
Almería 6277B
Almería 5060X
Almería 6340X
Almería 6293X
Araba/Álava 9122I
Araba/Álava 1044X
Araba/Álava 1060X
Araba/Álava 9060X
Araba/Álava 9073X
Araba/Álava 9091R
Araba/Álava 9145X
Araba/Álava 9178X
Asturias 1179B
Asturias 1331D
Asturias 1542
Asturias 1331A
Asturias 1327A
Asturias 1309C
Asturias 1302F
Asturias 1283U
Asturias 1341B
Asturias 1276F
Asturias 1183X
Asturias 1186P
Asturias 1279X
Asturias 1199X
Asturias 1203D
Asturias 1207U
Asturias 1210X
Asturias 1221D
Asturias 1223P
Asturias 1226X
Asturias 1234P
Asturias 1249X
Asturias 1272B
Asturias 1212E
Badajoz 4478X
Badajoz 4492E
Badajoz 4486X
Badajoz 4489X
Badajoz 4497X
Badajoz 5473X
Badajoz 4501X
Badajoz 4511C
Badajoz 4520X
Badajoz 4468X
Badajoz 4499X
Badajoz 4464X
Badajoz 4410X
Badajoz 4436Y
Badajoz 4427X
Badajoz 4395X
Badajoz 4386B
Badajoz 4358X
Badajoz 4340
Badajoz 4325X
Badajoz 4260
Badajoz 4244X
Badajoz 4452
Barcelona 0201D
Barcelona 0201X
Barcelona 0222X
Barcelona 0229I
Barcelona 0244X
Barcelona 0341X
Barcelona 0255B
Barcelona 0260X
Barcelona 0194D
Barcelona 0349
Barcelona 0252D
Barcelona 0171X
Barcelona 0114X
Barcelona 0149X
Barcelona 0120X
Barcelona 0106X
Barcelona 0092X
Barcelona 0076
Barcelona 0073X
Barcelona 0066X
Barcelona 0061X
Barcelona 0158X
Bizkaia 1069Y
Bizkaia 1082
Bizkaia 1083B
Bizkaia 1078C
Bizkaia 1074C
Bizkaia 1064L
Bizkaia 1078I
Bizkaia 1057B
Bizkaia 1056K
Bizkaia 1055B
Bizkaia 1059X
Burgos 2285B
Burgos 9111
Burgos 9069C
Burgos 9051
Burgos 9027X
Burgos 9012E
Burgos 2331X
Burgos 9031C
Burgos 2302N
Burgos 2298
Burgos 2290Y
Burgos 2117D
Burgos 2106B
Burgos 2311Y
Cantabria 1174I
Cantabria 1167B
Cantabria 1159
Cantabria 1154H
Cantabria 1152C
Cantabria 1124E
Cantabria 1096X
Cantabria 1111X
Cantabria 1102D
Cantabria 1109
Cantabria 1176A
Cantabria 1135C
Cantabria 1740
Cantabria 1083L
Cantabria 9016X
Cantabria 9019B
Cantabria 1089U
Cantabria 9001S
Cantabria 9001D
Castelló/Castellón 8439X
Castelló/Castellón 8472A
Castelló/Castellón 8489X
Castelló/Castellón 8492X
Castelló/Castellón 8500A
Castelló/Castellón 8520X
Castelló/Castellón 9563X
Castelló/Castellón 9562X
Castelló/Castellón 8503Y
Castelló/Castellón 8523X
Ceuta 5000C
Ciudad Real 4300Y
Ciudad Real 4064Y
Ciudad Real 4103X
Ciudad Real 4121
Ciudad Real 4138Y
Ciudad Real 4147X
Ciudad Real 4148
Ciudad Real 4210Y
Ciudad Real 4220X
Ciudad Real 5304Y
Ciudad Real 5341C
Cuenca 4090Y
Cuenca 3040Y
Cuenca 4075Y
Cuenca 3094B
Cuenca 4051Y
Cuenca 4070Y
Cuenca 4089A
Cuenca 4093Y
Cuenca 3044X
Cuenca 8096
Cuenca 8155Y
Cuenca 8210Y
Cuenca 8245Y
Cuenca 4095Y
Cáceres 3386A
Cáceres 3463X
Cáceres 3423I
Cáceres 3434X
Cáceres 3436D
Cáceres 3448X
Cáceres 3455X
Cáceres 4411C
Cáceres 3469A
Cáceres 3494U
Cáceres 4347X
Cáceres 3475X
Cáceres 4245X
Cáceres 3576X
Cáceres 3565X
Cáceres 3562X
Cáceres 3547X
Cáceres 3540X
Cáceres 4339X
Cáceres 3531X
Cáceres 3526X
Cáceres 3519X
Cáceres 3516X
Cáceres 3514B
Cáceres 3512X
Cáceres 3504X
Cáceres 3503
Cáceres 3536X
Cádiz 5910X
Cádiz 5911A
Cádiz 5919X
Cádiz 5941X
Cádiz 5950X
Cádiz 5960
Cádiz 5996B
Cádiz 5973
Cádiz 5983X
Cádiz 5995B
Cádiz 6001
Cádiz 6042I
Cádiz 6056X
Cádiz 5972X
Cádiz 5906X
Córdoba 5598X
Córdoba 5624X
Córdoba 4267X
Córdoba 5625X
Córdoba 5346X
Córdoba 5361X
Córdoba 5394X
Córdoba 5402
Córdoba 5390Y
Córdoba 5427X
Córdoba 5429X
Córdoba 5459X
Córdoba 5470
Córdoba 4263X
Córdoba 5412X
Gipuzkoa 1048X
Gipuzkoa 1025A
Gipuzkoa 1052A
Gipuzkoa 1050J
Gipuzkoa 1049N
Gipuzkoa 1041A
Gipuzkoa 1036A
Gipuzkoa 1037Y
Gipuzkoa 1037X
Gipuzkoa 1026X
Gipuzkoa 1025X
Gipuzkoa 1021X
Gipuzkoa 1014A
Gipuzkoa 1012P
Gipuzkoa 1038X
Girona 0411X
Girona 9585
Girona 0433D
Girona 0429X
Girona 0421X
Girona 0413A
Girona 0394X
Girona 0360X
Girona 0372C
Girona 0370E
Girona 0367
Girona 0363X
Girona 0324A
Girona 0320I
Girona 0312X
Girona 0281Y
Girona 0284X
Girona 0385X
Granada 5107D
Granada 5514Z
Granada 5051X
Granada 6281X
Granada 6272X
Granada 6258X
Granada 6268X
Granada 6267X
Granada 5582A
Granada 5530E
Granada 5515X
Granada 5515D
Granada 5047E
Granada 6268Y
Guadalajara 9377Y
Guadalajara 3209Y
Guadalajara 3103
Guadalajara 3158D
Guadalajara 3013
Guadalajara 3021Y
Guadalajara 3085Y
Guadalajara 3130C
Guadalajara 3168D
Guadalajara 3140Y
Huelva 4584X
Huelva 4589X
Huelva 4608X
Huelva 4622X
Huelva 4642E
Huelva 5769X
Huelva 5858X
Huelva 5860E
Huelva 4560Y
Huelva 4527X
Huelva 4554X
Huelva 4549Y
Huelva 4575X
Huelva 4541X
Huesca 9918Y
Huesca 9908X
Huesca 9924X
Huesca 9911X
Huesca 9445L
Huesca 9814I
Huesca 9894X
Huesca 9814X
Huesca 9839V
Huesca 9901X
Huesca 9451F
Huesca 9898
Huesca 9894Y
Huesca 9866C
Huesca 9207
Huesca 9208E
Huesca 9198X
Huesca 9211F
Huesca 9453X
Huesca 9460X
Huesca 9201K
Huesca 9751
Huesca 9491X
Huesca 9784P
Huesca 9808X
Huesca 9814A
Huesca 9838B
Huesca 9843A
Huesca 9855E
Huesca 9756X
Illes Balears B870C
Illes Balears B860X
Illes Balears B893
Illes Balears B908X
Illes Balears B954
Illes Balears B957
Illes Balears B228D
Illes Balears B925
Illes Balears B103B
Illes Balears B800X
Illes Balears B825B
Illes Balears B051A
Illes Balears B640X
Illes Balears B986
Illes Balears B780X
Illes Balears B644B
Illes Balears B691Y
Illes Balears B087X
Illes Balears B158X
Illes Balears B228
Illes Balears B236C
Illes Balears B248
Illes Balears B760X
Illes Balears B496X
Illes Balears B434X
Illes Balears B410B
Illes Balears B373X
Illes Balears B275C
Illes Balears B278
Illes Balears B362X
Illes Balears B346X
Illes Balears B334X
Illes Balears B013X
Illes Balears B301
Illes Balears B278C
Illes Balears B684A
Illes Balears B662X
Illes Balears B656A
Illes Balears B614E
Illes Balears B605X
Illes Balears B603X
Illes Balears B569X
Illes Balears B526X
Jaén 5279X
Jaén 5281X
Jaén 5038X
Jaén 5165X
Jaén 5181D
Jaén 5192
Jaén 5210X
Jaén 5246
Jaén 5270B
Jaén 5406X
Jaén 5164B
Jaén 5298X
La Rioja 9293X
La Rioja 9283Y
La Rioja 9188
La Rioja 9170
La Rioja 9145Y
La Rioja 9141V
La Rioja 9136X
La Rioja 9121X
La Rioja 9115X
Las Palmas C614H
Las Palmas C659H
Las Palmas C839I
Las Palmas C689E
Las Palmas C669B
Las Palmas C665T
Las Palmas C659M
Las Palmas C668V
Las Palmas C658X
Las Palmas C611E
Las Palmas C649R
Las Palmas C629X
Las Palmas C629Q
Las Palmas C628B
Las Palmas C625O
Las Palmas C623I
Las Palmas C619X
Las Palmas C619I
Las Palmas C612F
Las Palmas C635B
Las Palmas C259X
Las Palmas C249I
Las Palmas C248E
Las Palmas C229J
Las Palmas C048W
Las Palmas C038N
Las Palmas C029O
Las Palmas C019V
Las Palmas C018J
Las Palmas C258K
Las Palmas C656V
Las Palmas C239N
Las Palmas C649I
Las Palmas C648N
Las Palmas C648C
Las Palmas C639U
Las Palmas C639M
León 2742R
León 1178Y
León 2661
León 1541B
León 1549
León 1561I
León 2737E
León 2626Y
León 2630X
León 2661B
León 2664B
León 2701D
León 2728B
León 2734D
León 2624C
Lleida 9988B
Lleida 9677
Lleida 9990X
Lleida 9718X
Lleida 9590
Lleida 9590D
Lleida 9619
Lleida 9632X
Lleida 9744B
Lleida 9638D
Lleida 9771C
Lleida 9772X
Lleida 9775X
Lleida 9994X
Lleida 9729X
Lleida 9720X
Lleida 9698U
Lleida 9689X
Lleida 9657X
Lleida 9650X
Lleida 9647X
Lleida 9707
Lleida 9724X
Lugo 1535I
Lugo 1679A
Lugo 1342X
Lugo 1344X
Lugo 1347T
Lugo 1505
Lugo 1518A
Lugo 1521I
Lugo 1446X
Lugo 1297E
Lugo 1658
Lugo 1521X
Madrid 3194Y
Madrid 3195
Madrid 3229Y
Madrid 3266A
Madrid 3268C
Madrid 3330Y
Madrid 3338
Madrid 3343Y
Madrid 3272M
Madrid 3194U
Madrid 3182Y
Madrid 3191E
Madrid 3129
Madrid 3126Y
Madrid 3125Y
Madrid 3111D
Madrid 3110C
Madrid 3104Y
Madrid 3100B
Madrid 3344E
Madrid 2462
Madrid 3170Y
Melilla 6000A
Murcia 7218X
Murcia 7211B
Murcia 7227X
Murcia 7203A
Murcia 7250C
Murcia 7275C
Murcia 7209
Murcia 7237E
Murcia 7019B
Murcia 7138B
Murcia 7178I
Murcia 7002Y
Murcia 7007X
Murcia 7012C
Murcia 7195X
Murcia 7026X
Murcia 7031X
Murcia 7080X
Murcia 7023X
Murcia 7121A
Murcia 7127X
Murcia 7145D
Murcia 7158X
Murcia 7172X
Murcia 7119B
Málaga 6050X
Málaga 6205X
Málaga 6172O
Málaga 6032B
Málaga 6032X
Málaga 6040X
Málaga 6045X
Málaga 6057X
Málaga 6069X
Málaga 6156X
Málaga 6076X
Málaga 6083X
Málaga 6084X
Málaga 6088X
Málaga 6106X
Málaga 6127X
Málaga 6143X
Málaga 6155A
Málaga 6375X
Málaga 6172X
Málaga 6175X
Málaga 6199B
Málaga 6058I
Málaga 6201X
Málaga 6213X
Navarra 9283X
Navarra 1002Y
Navarra 1010X
Navarra 1033X
Navarra 9171K
Navarra 9294E
Navarra 9301X
Navarra 9302Y
Navarra 9995Y
Navarra 9274X
Navarra 9263X
Navarra 9263D
Navarra 9262P
Navarra 9257X
Navarra 9252X
Navarra 9245X
Navarra 9238X
Navarra 9228J
Navarra 9174
Navarra 9218A
Navarra 9280B
Navarra 9228T
Ourense 1639X
Ourense 1738U
Ourense 2978X
Ourense 2969U
Ourense 1706A
Ourense 1701X
Ourense 1735X
Ourense 1696O
Ourense 1690A
Ourense 1631E
Ourense 1583X
Ourense 1700X
Palencia 2401X
Palencia 2235U
Palencia 2243A
Palencia 2276B
Palencia 2362C
Palencia 2400E
Palencia 2568D
Palencia 2374X
Pontevedra 1495
Pontevedra 1466A
Pontevedra 1730E
Pontevedra 1723X
Pontevedra 1719
Pontevedra 1496X
Pontevedra 1468X
Pontevedra 1489A
Pontevedra 1484C
Pontevedra 1477V
Salamanca 2867
Salamanca 2930Y
Salamanca 2926B
Salamanca 2918Y
Salamanca 2863C
Salamanca 2916A
Salamanca 2914C
Salamanca 2891A
Salamanca 2883R
Salamanca 2873X
Salamanca 2945A
Salamanca 2946X
Salamanca 2870
Salamanca 2847X
Salamanca 2491C
Santa Cruz de Tenerife C438N
Santa Cruz de Tenerife C446G
Santa Cruz de Tenerife C447A
Santa Cruz de Tenerife C449C
Santa Cruz de Tenerife C449F
Santa Cruz de Tenerife C457I
Santa Cruz de Tenerife C458A
Santa Cruz de Tenerife C459Z
Santa Cruz de Tenerife C468B
Santa Cruz de Tenerife C469N
Santa Cruz de Tenerife C916Q
Santa Cruz de Tenerife C917E
Santa Cruz de Tenerife C925F
Santa Cruz de Tenerife C929I
Santa Cruz de Tenerife C939T
Santa Cruz de Tenerife C316I
Santa Cruz de Tenerife C101A
Santa Cruz de Tenerife C439J
Santa Cruz de Tenerife C430E
Santa Cruz de Tenerife C148F
Santa Cruz de Tenerife C428T
Santa Cruz de Tenerife C117A
Santa Cruz de Tenerife C117Z
Santa Cruz de Tenerife C126A
Santa Cruz de Tenerife C129V
Santa Cruz de Tenerife C429I
Santa Cruz de Tenerife C139E
Santa Cruz de Tenerife C314Z
Santa Cruz de Tenerife C129Z
Santa Cruz de Tenerife C317B
Santa Cruz de Tenerife C319W
Santa Cruz de Tenerife C328W
Santa Cruz de Tenerife C329Z
Santa Cruz de Tenerife C406G
Santa Cruz de Tenerife C419X
Santa Cruz de Tenerife C315P
Segovia 2482B
Segovia 2135A
Segovia 2471Y
Segovia 2465
Segovia 2192C
Segovia 2182C
Segovia 2150H
Segovia 2140A
Sevilla 5788X
Sevilla 5733X
Sevilla 5790Y
Sevilla 5612B
Sevilla 5612X
Sevilla 5641X

Sevilla 5654X
Sevilla 5656
Sevilla 5702X
Sevilla 5704B
Sevilla 5726X
Sevilla 5783
Sevilla 5796
Sevilla 5835X
Sevilla 5891X
Sevilla 5998X
Soria 2296A
Soria 9287A
Soria 2048A
Soria 9352A
Soria 2096B
Soria 9344C
Soria 2092
Soria 2030
Soria 2059B
Soria 2044B
Soria 2017Y
Soria 2005Y
Soria 2084Y
Tarragona 9947X
Tarragona 0002I
Tarragona 0009X
Tarragona 0016A
Tarragona 0034X
Tarragona 0042Y
Tarragona 9726E
Tarragona 9946X
Tarragona 9961X
Tarragona 9975X
Tarragona 9987P
Tarragona 9981A
Teruel 8486X
Teruel 8368U
Teruel 8354X
Teruel 9374X
Teruel 9381I
Teruel 9436X
Teruel 9513X
Teruel 9531Y
Teruel 9546B
Teruel 9550C
Teruel 9561X
Teruel 8376
Teruel 9569A
Teruel 9935X
Teruel 9998X
Teruel 9573X
Teruel 8458X
Toledo 3099Y
Toledo 3245Y
Toledo 3254Y
Toledo 3260B
Toledo 3298X
Toledo 3305Y
Toledo 3427Y
Toledo 4236Y
Toledo 4067
Toledo 3362Y
Toledo 4061X
Toledo 3365A
Valladolid 2593D
Valladolid 2517A
Valladolid 2507Y
Valladolid 2503X
Valladolid 2503B
Valladolid 2422
Valladolid 2172Y
Valladolid 2604B
Valladolid 2166Y
València/Valencia 8072Y
València/Valencia 8058Y
València/Valencia 8058X
València/Valencia 8290X
València/Valencia 8293X
València/Valencia 8309X
València/Valencia 8283X
València/Valencia 8300X
València/Valencia 8203O
València/Valencia 8395X
València/Valencia 8325X
València/Valencia 8337X
València/Valencia 8381X
València/Valencia 8409X
València/Valencia 8414A
València/Valencia 8416Y
València/Valencia 8446Y
València/Valencia 8005X
València/Valencia 8193E
València/Valencia 8319X
València/Valencia 8270X
Zamora 2789H
Zamora 2804F
Zamora 2536D
Zamora 2555B
Zamora 2611D
Zamora 2614
Zamora 2755X
Zamora 2766E
Zamora 2775X
Zamora 2777K
Zamora 2882D
Zamora 2885K
Zamora 2966D
Zaragoza 9244X
Zaragoza 9299X
Zaragoza 9576C
Zaragoza 9321X
Zaragoza 9510X
Zaragoza 9501X
Zaragoza 9574B
Zaragoza 9495Y
Zaragoza 9443V
Zaragoza 9434P
Zaragoza 9574X
Zaragoza 9394X
Zaragoza 9390
Zaragoza 9354X
Zaragoza 9336D
Zaragoza 9434
Zaragoza 9427X
Ávila 2430Y
Ávila 2444
Ávila 2453E
Ávila 2456B
Ávila 2811A
Ávila 2828Y
Ávila 3319D
Ávila 3391
Ávila 3422D
Ávila 2512Y
Ávila 3337U

In [57]:
# variable to hold the count
cnt = 0
  
# list to hold visited values
visited = []
  
# loop for counting the unique
# values in height
for i in range(0, len(listado_estaciones['Provincia'])):
    
    if listado_estaciones['Provincia'][i] not in visited: 
        
        visited.append(listado_estaciones['Provincia'][i])
          
        cnt += 1
  
print("No.of.unique values :",
      cnt)
  
print("unique values :",
      visited)

No.of.unique values : 52
unique values : ['A Coruña', 'Albacete', 'Alacant/Alicante', 'Almería', 'Araba/Álava', 'Asturias', 'Ávila', 'Badajoz', 'Barcelona', 'Bizkaia', 'Burgos', 'Cáceres', 'Cádiz', 'Cantabria', 'Castelló/Castellón', 'Ceuta', 'Ciudad Real', 'Córdoba', 'Cuenca', 'Gipuzkoa', 'Girona', 'Granada', 'Guadalajara', 'Huelva', 'Huesca', 'Illes Balears', 'Jaén', 'La Rioja', 'Las Palmas', 'León', 'Lleida', 'Lugo', 'Madrid', 'Málaga', 'Melilla', 'Murcia', 'Navarra', 'Ourense', 'Palencia', 'Pontevedra', 'Salamanca', 'Segovia', 'Sevilla', 'Soria', 'Santa Cruz de Tenerife', 'Tarragona', 'Teruel', 'Toledo', 'València/Valencia', 'Valladolid', 'Zamora', 'Zaragoza']

In [58]:
#Here I'm randomly selecting one weather station for each province, excluding the Balearic and Canary Islands
#Also Ceuta and Melilla
s0 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("A Coruña")].sample(1, random_state=1).index
s1 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Albacete")].sample(1, random_state=1).index
s2 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Alacant/Alicante")].sample(1, random_state=1).index
s3 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Almería")].sample(1, random_state=1).index
s4 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Araba/Álava")].sample(1, random_state=1).index
s5 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Asturias")].sample(1, random_state=1).index
s6 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Ávila")].sample(1, random_state=1).index
s7 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Badajoz")].sample(1, random_state=1).index
s8 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Barcelona")].sample(1, random_state=1).index
s9 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Bizkaia")].sample(1, random_state=1).index
s10 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Burgos")].sample(1, random_state=1).index
s11 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Cáceres")].sample(1, random_state=1).index
s12 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Cádiz")].sample(1, random_state=1).index
s13 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Cantabria")].sample(1, random_state=1).index
s14 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Castelló/Castellón")].sample(1, random_state=1).index
s15 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Ciudad Real")].sample(1, random_state=1).index
s16 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Córdoba")].sample(1, random_state=1).index
s17 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Cuenca")].sample(1, random_state=1).index
s18 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Gipuzkoa")].sample(1, random_state=1).index
s19 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Girona")].sample(1, random_state=1).index
s20 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Granada")].sample(1, random_state=1).index
s21 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Guadalajara")].sample(1, random_state=1).index
s22 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Huelva")].sample(1, random_state=1).index
s23 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Huesca")].sample(1, random_state=1).index
s24 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Jaén")].sample(1, random_state=1).index
s25 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("La Rioja")].sample(1, random_state=1).index
s26 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("León")].sample(1, random_state=1).index
s27 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Lleida")].sample(1, random_state=1).index
s28 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Lugo")].sample(1, random_state=1).index
s29 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Madrid")].sample(1, random_state=1).index
s30 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Málaga")].sample(1, random_state=1).index
s31 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Murcia")].sample(1, random_state=1).index
s32 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Navarra")].sample(1, random_state=1).index
s33 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Ourense")].sample(1, random_state=1).index
s34 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Palencia")].sample(1, random_state=1).index
s35 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Pontevedra")].sample(1, random_state=1).index
s36 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Salamanca")].sample(1, random_state=1).index
s37 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Segovia")].sample(1, random_state=1).index
s38 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Sevilla")].sample(1, random_state=1).index
s39 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Soria")].sample(1, random_state=1).index
s40 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Tarragona")].sample(1, random_state=1).index
s41 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Teruel")].sample(1, random_state=1).index
s42 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Toledo")].sample(1, random_state=1).index
s43 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("València/Valencia")].sample(1, random_state=1).index
s44 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Valladolid")].sample(1, random_state=1).index
s45 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Zamora")].sample(1, random_state=1).index
s46 = listado_estaciones.Provincia[listado_estaciones.Provincia.eq("Zaragoza")].sample(1, random_state=1).index

random_weather_stations = listado_estaciones.loc[s0.union(s1).union(s2).union(s3).union(s4).union(s5).union(s6).union(s7).union(s8).
                            union(s9).union(s10).union(s11).union(s12).union(s13).union(s14).union(s15).union(s16).
                           union(s17).union(s18).union(s19).union(s20).union(s21).union(s22).union(s23).union(s24).
                           union(s25).union(s26).union(s27).union(s28).union(s29).union(s30).union(s31).union(s32).
                           union(s33).union(s34).union(s35).union(s36).union(s37).union(s38).union(s39).union(s40).
                           union(s41).union(s42).union(s43).union(s44).union(s45).union(s46)]
random_weather_stations

,Identificador_est,Nombre_est,Municipio,Provincia,Altura,Longitud,Latitud
11,1442U,Boiro,Boiro,A Coruña,10,423838N,085332W
36,8057C,Pego,Pego,Alacant/Alicante,60,385048N,000706W
48,6367B,Huercal Overa,Huércal-Overa,Almería,300,372326N,015637W
56,9178X,Campezo/Kanpezu,Campezo/Kanpezu,Araba/Álava,570,424014N,022046W
60,1199X,Piloña,Piloña,Asturias,280,432240N,052348W
82,2453E,Gotarrendura,Gotarrendura,Ávila,920,404944N,044431W
91,4260,Peraleda del Zaucejo,Peraleda del Zaucejo,Badajoz,542,382847N,053439W
114,0066X,Vilafranca del Penedès,Vilafranca del Penedès,Barcelona,177,411949N,014037E
145,1083B,Sopuerta,Sopuerta,Bizkaia,177,431647N,031007W
156,9051,Medina de Pomar,Medina de Pomar,Burgos,580,425512N,032858W
171,3512X,Montehermoso,Montehermoso,Cáceres,351,400451N,062020W
191,5941X,El Bosque,"Bosque, El",Cádiz,295,364346N,053044W
211,1154H,"Torrelavega, Sierrapando",Torrelavega,Cantabria,110,432131N,040139W
222,8489X,Villafranca del Cid/Villafranca,Villafranca del Cid/Vilafranca,Castelló/Castellón,1131,402600N,001521W
231,4103X,Tomelloso,Tomelloso,Ciudad Real,662,391009N,030027W
255,5625X,La Rambla,"Rambla, La",Córdoba,200,373819N,044550W
258,3094B,Tarancón,Tarancón,Cuenca,808,400041N,030117W
281,1050J,Elgoibar,Elgoibar,Gipuzkoa,120,431234N,022448W
294,0394X,La Vall de Bianya,"Vall de Bianya, La",Girona,350,421238N,022819E
311,6281X,Válor,Válor,Granada,1020,370019N,030417W
315,3103,Retiendas,Retiendas,Guadalajara,910,410013N,031807W
331,4622X,Villarrasa,Villarrasa,Huelva,145,372703N,063812W
340,9211F,Bailo,Bailo,Huesca,722,423051N,004902W
397,5038X,Cazorla,Cazorla,Jaén,813,375457N,030014W
409,9115X,"Valdezcaray, estación de esquí",Ezcaray,La Rioja,1630,421518N,025806W
453,1541B,Villablino,Villablino,León,958,425544N,062002W
471,9647X,Torà,Torà,Lleida,435,414821N,012344E
486,1342X,Ribadeo,Ribadeo,Lugo,43,433226N,070459W
528,6106X,Antequera,Antequera,Málaga,408,370146N,044454W
555,7195X,"Caravaca de La Cruz, Los Royos",Caravaca de la Cruz,Murcia,985,375534N,020330W
568,9218A,Isaba/Izaba,Isaba/Izaba,Navarra,820,425144N,005529W
596,2978X,Verín,Verín,Ourense,380,415536N,072519W
601,2374X,Carrión de los Condes,Carrión de los Condes,Palencia,830,422103N,043702W
614,1730E,O Rosal,"Rosal, O",Pontevedra,55,415638N,085051W
625,2918Y,El Maíllo,"Maíllo, El",Salamanca,1027,403410N,061325W
631,2140A,Aldeanueva de Serrezuela,Aldeanueva de la Serrezuela,Segovia,1135,412752N,034709W
638,5612B,La Roda de Andalucía,"Roda de Andalucía, La",Sevilla,410,371140N,044612W
657,2048A,Morón de Almazán,Morón de Almazán,Soria,978,412510N,022513W
701,0009X,Alforja,Alforja,Tarragona,406,411250N,005748E
717,9374X,"Teruel, Santa Eulalia del Campo",Santa Eulalia,Teruel,1000,403400N,011915W
731,3254Y,Mora,Mora,Toledo,717,394113N,034650W
759,8416Y,Valencia,Valencia,València/Valencia,11,392850N,002159W
761,2166Y,Peñafiel,Peñafiel,Valladolid,756,413535N,040729W
770,2536D,Morales del Toro,Morales de Toro,Zamora,710,413255N,051618W
785,9321X,Ejea de los Caballeros,Ejea de los Caballeros,Zaragoza,321,420716N,010823W
816,8175,Albacete Base Aérea,Albacete,Albacete,702,385715N,015123W
829,3344E,Villanueva de la Cañada,Villanueva de la Cañada,Madrid,641,402615N,040119W

In [59]:
len(random_weather_stations)

47

In [60]:
identificadores = random_weather_stations["Identificador_est"]
identificadores =list(identificadores)
identificadores

['1442U',
 '8057C',
 '6367B',
 '9178X',
 '1199X',
 '2453E',
 '4260',
 '0066X',
 '1083B',
 '9051',
 '3512X',
 '5941X',
 '1154H',
 '8489X',
 '4103X',
 '5625X',
 '3094B',
 '1050J',
 '0394X',
 '6281X',
 '3103',
 '4622X',
 '9211F',
 '5038X',
 '9115X',
 '1541B',
 '9647X',
 '1342X',
 '6106X',
 '7195X',
 '9218A',
 '2978X',
 '2374X',
 '1730E',
 '2918Y',
 '2140A',
 '5612B',
 '2048A',
 '0009X',
 '9374X',
 '3254Y',
 '8416Y',
 '2166Y',
 '2536D',
 '9321X',
 '8175',
 '3344E']

In [61]:
path_datos_estaciones = "/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Aemet2021-06-Por-Estaciones/DatosEstaciones - 2021-06/Randomly_selected_1/"

In [62]:
#This reads all the relevant weather stations csv:

import pandas as pd
import glob

path = path_datos_estaciones

all_relevant_files = glob.glob(path + "*.csv")

li = []

for filename in all_relevant_files:
    df = pd.read_csv(filename, index_col=None, header=0, sep =";", dtype= str)
    li.append(df)

weather_data = pd.concat(li, axis=0, ignore_index=True)
weather_data

,Id,Fecha,Tmax,HTmax,Tmin,HTmin,Tmed,Racha,HRacha,Vmax,HVmax,TPrec,Prec1,Prec2,Prec3,Prec4
0,0009X,2013-05-07,25.4,17:40,14.6,00:30,20,44,16:30,24,09:40,0,0,0,0,0
1,0009X,2013-05-08,24.3,18:20,14.4,05:00,19.3,30,16:20,15,16:20,0,0,0,0,0
2,0009X,2013-05-09,21.6,16:50,12.7,05:00,17.2,25,23:20,16,23:59,1.8,0,0,0,1.8
3,0009X,2013-05-10,21.7,17:10,11.4,05:50,16.6,50,13:20,29,14:00,0,0,0,0,0
4,0009X,2013-05-11,22.3,16:40,10.8,01:00,16.5,46,13:30,26,13:50,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133091,9647X,2021-06-26,30.4,16:00,14.3,06:20,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0
133092,9647X,2021-06-27,32.2,15:00,14.3,06:10,23.3,NaN,NaN,NaN,NaN,0,0,0,0,0
133093,9647X,2021-06-28,29.1,17:30,15.4,06:00,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0
133094,9647X,2021-06-29,28.2,18:20,11.6,03:00,19.9,NaN,NaN,NaN,NaN,0,0,0,0,0
133095,9647X,2021-06-30,28.2,18:40,16.4,02:50,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0

In [63]:
weather_data.rename(columns = {"Id": "Identificador_est"}, inplace= True)

In [64]:
weather_data = pd.merge(weather_data, 
                     random_weather_stations, 
                     on ='Identificador_est',
                       how= "left")
weather_data

,Identificador_est,Fecha,Tmax,HTmax,Tmin,HTmin,Tmed,Racha,HRacha,Vmax,HVmax,TPrec,Prec1,Prec2,Prec3,Prec4,Nombre_est,Municipio,Provincia,Altura,Longitud,Latitud
0,0009X,2013-05-07,25.4,17:40,14.6,00:30,20,44,16:30,24,09:40,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E
1,0009X,2013-05-08,24.3,18:20,14.4,05:00,19.3,30,16:20,15,16:20,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E
2,0009X,2013-05-09,21.6,16:50,12.7,05:00,17.2,25,23:20,16,23:59,1.8,0,0,0,1.8,Alforja,Alforja,Tarragona,406,411250N,005748E
3,0009X,2013-05-10,21.7,17:10,11.4,05:50,16.6,50,13:20,29,14:00,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E
4,0009X,2013-05-11,22.3,16:40,10.8,01:00,16.5,46,13:30,26,13:50,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133091,9647X,2021-06-26,30.4,16:00,14.3,06:20,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E
133092,9647X,2021-06-27,32.2,15:00,14.3,06:10,23.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E
133093,9647X,2021-06-28,29.1,17:30,15.4,06:00,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E
133094,9647X,2021-06-29,28.2,18:20,11.6,03:00,19.9,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E
133095,9647X,2021-06-30,28.2,18:40,16.4,02:50,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E

In [65]:
poblacion_path = "/home/dsc/CarpetaCompartida/TFM/Data/Precios de la electricidad/Cifras oficiales de población resultantes de la revisión del Padrón municipal 2020.csv"

In [66]:
poblacion = pd.read_csv(poblacion_path, dtype = str, engine= "python", sep=";", encoding= "latin1")
poblacion

                   Provincias   Sexo Periodo      Total
0                 02 Albacete  Total    2020    388.270
1         03 Alicante/Alacant  Total    2020  1.879.888
2                  04 Almería  Total    2020    727.945
3              01 Araba/Álava  Total    2020    333.940
4                 33 Asturias  Total    2020  1.018.784
5                    05 Ávila  Total    2020    157.664
6                  06 Badajoz  Total    2020    672.137
7           07 Balears, Illes  Total    2020  1.171.543
8                08 Barcelona  Total    2020  5.743.402
9                  48 Bizkaia  Total    2020  1.159.443
10                  09 Burgos  Total    2020    357.650
11                 10 Cáceres  Total    2020    391.850
12                   11 Cádiz  Total    2020  1.244.049
13               39 Cantabria  Total    2020    582.905
14      12 Castellón/Castelló  Total    2020    585.590
15             13 Ciudad Real  Total    2020    495.045
16                 14 Córdoba  Total    2020    781.451
17               15 Coruña, A  Total    2020  1.121.815
18                  16 Cuenca  Total    2020    196.139
19                20 Gipuzkoa  Total    2020    727.121
20                  17 Girona  Total    2020    781.788
21                 18 Granada  Total    2020    919.168
22             19 Guadalajara  Total    2020    261.995
23                  21 Huelva  Total    2020    524.278
24                  22 Huesca  Total    2020    222.687
25                    23 Jaén  Total    2020    631.381
26                    24 León  Total    2020    456.439
27                  25 Lleida  Total    2020    438.517
28                    27 Lugo  Total    2020    327.946
29                  28 Madrid  Total    2020  6.779.888
30                  29 Málaga  Total    2020  1.685.920
31                  30 Murcia  Total    2020  1.511.251
32                 31 Navarra  Total    2020    661.197
33                 32 Ourense  Total    2020    306.650
34                34 Palencia  Total    2020    160.321
35             35 Palmas, Las  Total    2020  1.131.065
36              36 Pontevedra  Total    2020    945.408
37               26 Rioja, La  Total    2020    319.914
38               37 Salamanca  Total    2020    329.245
39  38 Santa Cruz de Tenerife  Total    2020  1.044.887
40                 40 Segovia  Total    2020    153.478
41                 41 Sevilla  Total    2020  1.950.219
42                   42 Soria  Total    2020     88.884
43               43 Tarragona  Total    2020    816.772
44                  44 Teruel  Total    2020    134.176
45                  45 Toledo  Total    2020    703.772
46       46 Valencia/València  Total    2020  2.591.875
47              47 Valladolid  Total    2020    520.649
48                  49 Zamora  Total    2020    170.588
49                50 Zaragoza  Total    2020    972.528
50                   51 Ceuta  Total    2020     84.202
51                 52 Melilla  Total    2020     87.076

In [67]:
poblacion[["Code", "Provincia"]] = poblacion.Provincias.str.split(" ",1, expand=True)
poblacion

,Provincias,Sexo,Periodo,Total,Code,Provincia
0,02 Albacete,Total,2020,388.270,02,Albacete
1,03 Alicante/Alacant,Total,2020,1.879.888,03,Alicante/Alacant
2,04 Almería,Total,2020,727.945,04,Almería
3,01 Araba/Álava,Total,2020,333.940,01,Araba/Álava
4,33 Asturias,Total,2020,1.018.784,33,Asturias
5,05 Ávila,Total,2020,157.664,05,Ávila
6,06 Badajoz,Total,2020,672.137,06,Badajoz
7,"07 Balears, Illes",Total,2020,1.171.543,07,"Balears, Illes"
8,08 Barcelona,Total,2020,5.743.402,08,Barcelona
9,48 Bizkaia,Total,2020,1.159.443,48,Bizkaia
10,09 Burgos,Total,2020,357.650,09,Burgos
11,10 Cáceres,Total,2020,391.850,10,Cáceres
12,11 Cádiz,Total,2020,1.244.049,11,Cádiz
13,39 Cantabria,Total,2020,582.905,39,Cantabria
14,12 Castellón/Castelló,Total,2020,585.590,12,Castellón/Castelló
15,13 Ciudad Real,Total,2020,495.045,13,Ciudad Real
16,14 Córdoba,Total,2020,781.451,14,Córdoba
17,"15 Coruña, A",Total,2020,1.121.815,15,"Coruña, A"
18,16 Cuenca,Total,2020,196.139,16,Cuenca
19,20 Gipuzkoa,Total,2020,727.121,20,Gipuzkoa
20,17 Girona,Total,2020,781.788,17,Girona
21,18 Granada,Total,2020,919.168,18,Granada
22,19 Guadalajara,Total,2020,261.995,19,Guadalajara
23,21 Huelva,Total,2020,524.278,21,Huelva
24,22 Huesca,Total,2020,222.687,22,Huesca
25,23 Jaén,Total,2020,631.381,23,Jaén
26,24 León,Total,2020,456.439,24,León
27,25 Lleida,Total,2020,438.517,25,Lleida
28,27 Lugo,Total,2020,327.946,27,Lugo
29,28 Madrid,Total,2020,6.779.888,28,Madrid
30,29 Málaga,Total,2020,1.685.920,29,Málaga
31,30 Murcia,Total,2020,1.511.251,30,Murcia
32,31 Navarra,Total,2020,661.197,31,Navarra
33,32 Ourense,Total,2020,306.650,32,Ourense
34,34 Palencia,Total,2020,160.321,34,Palencia
35,"35 Palmas, Las",Total,2020,1.131.065,35,"Palmas, Las"
36,36 Pontevedra,Total,2020,945.408,36,Pontevedra
37,"26 Rioja, La",Total,2020,319.914,26,"Rioja, La"
38,37 Salamanca,Total,2020,329.245,37,Salamanca
39,38 Santa Cruz de Tenerife,Total,2020,1.044.887,38,Santa Cruz de Tenerife
40,40 Segovia,Total,2020,153.478,40,Segovia
41,41 Sevilla,Total,2020,1.950.219,41,Sevilla
42,42 Soria,Total,2020,88.884,42,Soria
43,43 Tarragona,Total,2020,816.772,43,Tarragona
44,44 Teruel,Total,2020,134.176,44,Teruel
45,45 Toledo,Total,2020,703.772,45,Toledo
46,46 Valencia/València,Total,2020,2.591.875,46,Valencia/València
47,47 Valladolid,Total,2020,520.649,47,Valladolid
48,49 Zamora,Total,2020,170.588,49,Zamora
49,50 Zaragoza,Total,2020,972.528,50,Zaragoza
50,51 Ceuta,Total,2020,84.202,51,Ceuta
51,52 Melilla,Total,2020,87.076,52,Melilla

In [68]:
poblacion = poblacion.drop(["Provincias", "Sexo", "Periodo", "Code"], axis = 1)
poblacion

        Total               Provincia
0     388.270                Albacete
1   1.879.888        Alicante/Alacant
2     727.945                 Almería
3     333.940             Araba/Álava
4   1.018.784                Asturias
5     157.664                   Ávila
6     672.137                 Badajoz
7   1.171.543          Balears, Illes
8   5.743.402               Barcelona
9   1.159.443                 Bizkaia
10    357.650                  Burgos
11    391.850                 Cáceres
12  1.244.049                   Cádiz
13    582.905               Cantabria
14    585.590      Castellón/Castelló
15    495.045             Ciudad Real
16    781.451                 Córdoba
17  1.121.815               Coruña, A
18    196.139                  Cuenca
19    727.121                Gipuzkoa
20    781.788                  Girona
21    919.168                 Granada
22    261.995             Guadalajara
23    524.278                  Huelva
24    222.687                  Huesca
25    631.381                    Jaén
26    456.439                    León
27    438.517                  Lleida
28    327.946                    Lugo
29  6.779.888                  Madrid
30  1.685.920                  Málaga
31  1.511.251                  Murcia
32    661.197                 Navarra
33    306.650                 Ourense
34    160.321                Palencia
35  1.131.065             Palmas, Las
36    945.408              Pontevedra
37    319.914               Rioja, La
38    329.245               Salamanca
39  1.044.887  Santa Cruz de Tenerife
40    153.478                 Segovia
41  1.950.219                 Sevilla
42     88.884                   Soria
43    816.772               Tarragona
44    134.176                  Teruel
45    703.772                  Toledo
46  2.591.875       Valencia/València
47    520.649              Valladolid
48    170.588                  Zamora
49    972.528                Zaragoza
50     84.202                   Ceuta
51     87.076                 Melilla

In [69]:
poblacion["Provincia"].unique()

array(['Albacete', 'Alicante/Alacant', 'Almería', 'Araba/Álava',
       'Asturias', 'Ávila', 'Badajoz', 'Balears, Illes', 'Barcelona',
       'Bizkaia', 'Burgos', 'Cáceres', 'Cádiz', 'Cantabria',
       'Castellón/Castelló', 'Ciudad Real', 'Córdoba', 'Coruña, A',
       'Cuenca', 'Gipuzkoa', 'Girona', 'Granada', 'Guadalajara', 'Huelva',
       'Huesca', 'Jaén', 'León', 'Lleida', 'Lugo', 'Madrid', 'Málaga',
       'Murcia', 'Navarra', 'Ourense', 'Palencia', 'Palmas, Las',
       'Pontevedra', 'Rioja, La', 'Salamanca', 'Santa Cruz de Tenerife',
       'Segovia', 'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo',
       'Valencia/València', 'Valladolid', 'Zamora', 'Zaragoza', 'Ceuta',
       'Melilla'], dtype=object)

In [70]:
weather_data["Provincia"].unique()

array(['Tarragona', 'Barcelona', 'Girona', 'Gipuzkoa', 'Bizkaia',
       'Cantabria', 'Asturias', 'Lugo', 'A Coruña', 'León', 'Pontevedra',
       'Soria', 'Segovia', 'Valladolid', 'Palencia', 'Ávila', 'Zamora',
       'Salamanca', 'Ourense', 'Cuenca', 'Guadalajara', 'Toledo',
       'Madrid', 'Cáceres', 'Ciudad Real', 'Badajoz', 'Huelva', 'Jaén',
       'Sevilla', 'Córdoba', 'Cádiz', 'Málaga', 'Granada', 'Almería',
       'Murcia', 'Alacant/Alicante', 'Albacete', 'València/Valencia',
       'Castelló/Castellón', 'Burgos', 'La Rioja', 'Araba/Álava',
       'Huesca', 'Navarra', 'Zaragoza', 'Teruel', 'Lleida'], dtype=object)

In [71]:
provincias_stations = random_weather_stations["Provincia"]
provincias_stations = pd.DataFrame(provincias_stations).reset_index().drop(columns="index")
provincias_stations

             Provincia
0             A Coruña
1     Alacant/Alicante
2              Almería
3          Araba/Álava
4             Asturias
5                Ávila
6              Badajoz
7            Barcelona
8              Bizkaia
9               Burgos
10             Cáceres
11               Cádiz
12           Cantabria
13  Castelló/Castellón
14         Ciudad Real
15             Córdoba
16              Cuenca
17            Gipuzkoa
18              Girona
19             Granada
20         Guadalajara
21              Huelva
22              Huesca
23                Jaén
24            La Rioja
25                León
26              Lleida
27                Lugo
28              Málaga
29              Murcia
30             Navarra
31             Ourense
32            Palencia
33          Pontevedra
34           Salamanca
35             Segovia
36             Sevilla
37               Soria
38           Tarragona
39              Teruel
40              Toledo
41   València/Valencia
42          Valladolid
43              Zamora
44            Zaragoza
45            Albacete
46              Madrid

In [72]:
provincias_poblacion = poblacion["Provincia"]
provincias_poblacion = pd.DataFrame(provincias_poblacion).reset_index().drop(columns="index")
provincias_poblacion

                 Provincia
0                 Albacete
1         Alicante/Alacant
2                  Almería
3              Araba/Álava
4                 Asturias
5                    Ávila
6                  Badajoz
7           Balears, Illes
8                Barcelona
9                  Bizkaia
10                  Burgos
11                 Cáceres
12                   Cádiz
13               Cantabria
14      Castellón/Castelló
15             Ciudad Real
16                 Córdoba
17               Coruña, A
18                  Cuenca
19                Gipuzkoa
20                  Girona
21                 Granada
22             Guadalajara
23                  Huelva
24                  Huesca
25                    Jaén
26                    León
27                  Lleida
28                    Lugo
29                  Madrid
30                  Málaga
31                  Murcia
32                 Navarra
33                 Ourense
34                Palencia
35             Palmas, Las
36              Pontevedra
37               Rioja, La
38               Salamanca
39  Santa Cruz de Tenerife
40                 Segovia
41                 Sevilla
42                   Soria
43               Tarragona
44                  Teruel
45                  Toledo
46       Valencia/València
47              Valladolid
48                  Zamora
49                Zaragoza
50                   Ceuta
51                 Melilla

In [73]:
different_names = provincias_stations.merge(right = provincias_poblacion, how= "left", indicator=True)

different_names = different_names[different_names['_merge']=='left_only']
different_names

             Provincia     _merge
0             A Coruña  left_only
1     Alacant/Alicante  left_only
13  Castelló/Castellón  left_only
24            La Rioja  left_only
41   València/Valencia  left_only

In [74]:
#I'm changing the name in the population dataframe so it matches the weather stations one, for those that are not the same
poblacion.loc[17, "Provincia"] = "A Coruña"
poblacion.loc[1, "Provincia"] = "Alacant/Alicante"
poblacion.loc[14, "Provincia"] = "Castelló/Castellón"
poblacion.loc[37, "Provincia"] = "La Rioja"
poblacion.loc[46, "Provincia"] = "València/Valencia"

In [75]:
weather_data_population = weather_data.merge(right= poblacion, on= "Provincia", how= "left")
weather_data_population

,Identificador_est,Fecha,Tmax,HTmax,Tmin,HTmin,Tmed,Racha,HRacha,Vmax,HVmax,TPrec,Prec1,Prec2,Prec3,Prec4,Nombre_est,Municipio,Provincia,Altura,Longitud,Latitud,Total
0,0009X,2013-05-07,25.4,17:40,14.6,00:30,20,44,16:30,24,09:40,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
1,0009X,2013-05-08,24.3,18:20,14.4,05:00,19.3,30,16:20,15,16:20,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
2,0009X,2013-05-09,21.6,16:50,12.7,05:00,17.2,25,23:20,16,23:59,1.8,0,0,0,1.8,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
3,0009X,2013-05-10,21.7,17:10,11.4,05:50,16.6,50,13:20,29,14:00,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
4,0009X,2013-05-11,22.3,16:40,10.8,01:00,16.5,46,13:30,26,13:50,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133091,9647X,2021-06-26,30.4,16:00,14.3,06:20,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517
133092,9647X,2021-06-27,32.2,15:00,14.3,06:10,23.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517
133093,9647X,2021-06-28,29.1,17:30,15.4,06:00,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517
133094,9647X,2021-06-29,28.2,18:20,11.6,03:00,19.9,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517
133095,9647X,2021-06-30,28.2,18:40,16.4,02:50,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517

In [76]:
weather_data_population.rename(columns= {"Total": "Población"}, inplace=True)
weather_data_population

,Identificador_est,Fecha,Tmax,HTmax,Tmin,HTmin,Tmed,Racha,HRacha,Vmax,HVmax,TPrec,Prec1,Prec2,Prec3,Prec4,Nombre_est,Municipio,Provincia,Altura,Longitud,Latitud,Población
0,0009X,2013-05-07,25.4,17:40,14.6,00:30,20,44,16:30,24,09:40,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
1,0009X,2013-05-08,24.3,18:20,14.4,05:00,19.3,30,16:20,15,16:20,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
2,0009X,2013-05-09,21.6,16:50,12.7,05:00,17.2,25,23:20,16,23:59,1.8,0,0,0,1.8,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
3,0009X,2013-05-10,21.7,17:10,11.4,05:50,16.6,50,13:20,29,14:00,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
4,0009X,2013-05-11,22.3,16:40,10.8,01:00,16.5,46,13:30,26,13:50,0,0,0,0,0,Alforja,Alforja,Tarragona,406,411250N,005748E,816.772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133091,9647X,2021-06-26,30.4,16:00,14.3,06:20,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517
133092,9647X,2021-06-27,32.2,15:00,14.3,06:10,23.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517
133093,9647X,2021-06-28,29.1,17:30,15.4,06:00,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517
133094,9647X,2021-06-29,28.2,18:20,11.6,03:00,19.9,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517
133095,9647X,2021-06-30,28.2,18:40,16.4,02:50,22.3,NaN,NaN,NaN,NaN,0,0,0,0,0,Torà,Torà,Lleida,435,414821N,012344E,438.517

In [77]:
weather_data_population = weather_data_population.drop({"HTmax", "HTmin", "Racha", "HRacha", 
                                                        "HVmax", "Prec1", "Prec2", "Prec3", "Prec4", "Municipio" },
                                                       axis = 1)
weather_data_population

,Identificador_est,Fecha,Tmax,Tmin,Tmed,Vmax,TPrec,Nombre_est,Provincia,Altura,Longitud,Latitud,Población
0,0009X,2013-05-07,25.4,14.6,20,24,0,Alforja,Tarragona,406,411250N,005748E,816.772
1,0009X,2013-05-08,24.3,14.4,19.3,15,0,Alforja,Tarragona,406,411250N,005748E,816.772
2,0009X,2013-05-09,21.6,12.7,17.2,16,1.8,Alforja,Tarragona,406,411250N,005748E,816.772
3,0009X,2013-05-10,21.7,11.4,16.6,29,0,Alforja,Tarragona,406,411250N,005748E,816.772
4,0009X,2013-05-11,22.3,10.8,16.5,26,0,Alforja,Tarragona,406,411250N,005748E,816.772
...,...,...,...,...,...,...,...,...,...,...,...,...,...
133091,9647X,2021-06-26,30.4,14.3,22.3,NaN,0,Torà,Lleida,435,414821N,012344E,438.517
133092,9647X,2021-06-27,32.2,14.3,23.3,NaN,0,Torà,Lleida,435,414821N,012344E,438.517
133093,9647X,2021-06-28,29.1,15.4,22.3,NaN,0,Torà,Lleida,435,414821N,012344E,438.517
133094,9647X,2021-06-29,28.2,11.6,19.9,NaN,0,Torà,Lleida,435,414821N,012344E,438.517
133095,9647X,2021-06-30,28.2,16.4,22.3,NaN,0,Torà,Lleida,435,414821N,012344E,438.517

In [78]:
weather_data_population.isnull().any()

Identificador_est    False
Fecha                False
Tmax                  True
Tmin                  True
Tmed                  True
Vmax                  True
TPrec                 True
Nombre_est           False
Provincia            False
Altura               False
Longitud             False
Latitud              False
Población            False
dtype: bool

In [79]:
weather_data_population.isnull().sum()

Identificador_est        0
Fecha                    0
Tmax                  8793
Tmin                  8793
Tmed                  8793
Vmax                 32893
TPrec                10609
Nombre_est               0
Provincia                0
Altura                   0
Longitud                 0
Latitud                  0
Población                0
dtype: int64

In [80]:
nan_rows = weather_data_population[weather_data_population.isnull().any(1)]
nan_rows

,Identificador_est,Fecha,Tmax,Tmin,Tmed,Vmax,TPrec,Nombre_est,Provincia,Altura,Longitud,Latitud,Población
12,0009X,2013-05-19,NaN,NaN,NaN,NaN,NaN,Alforja,Tarragona,406,411250N,005748E,816.772
99,0009X,2013-08-14,NaN,NaN,NaN,NaN,NaN,Alforja,Tarragona,406,411250N,005748E,816.772
100,0009X,2013-08-15,NaN,NaN,NaN,NaN,NaN,Alforja,Tarragona,406,411250N,005748E,816.772
101,0009X,2013-08-16,NaN,NaN,NaN,NaN,NaN,Alforja,Tarragona,406,411250N,005748E,816.772
118,0009X,2013-09-02,NaN,NaN,NaN,NaN,NaN,Alforja,Tarragona,406,411250N,005748E,816.772
...,...,...,...,...,...,...,...,...,...,...,...,...,...
133091,9647X,2021-06-26,30.4,14.3,22.3,NaN,0,Torà,Lleida,435,414821N,012344E,438.517
133092,9647X,2021-06-27,32.2,14.3,23.3,NaN,0,Torà,Lleida,435,414821N,012344E,438.517
133093,9647X,2021-06-28,29.1,15.4,22.3,NaN,0,Torà,Lleida,435,414821N,012344E,438.517
133094,9647X,2021-06-29,28.2,11.6,19.9,NaN,0,Torà,Lleida,435,414821N,012344E,438.517
133095,9647X,2021-06-30,28.2,16.4,22.3,NaN,0,Torà,Lleida,435,414821N,012344E,438.517

In [81]:
#I'm going to fill the NaN values with the last valid observation. 
#I'm assuming the first row of each different weather stations never has any NaN values.
#That must not always be the case, but let's assume that for now.

weather_data_population_noNan = weather_data_population.fillna(method= "ffill")
weather_data_population_noNan

,Identificador_est,Fecha,Tmax,Tmin,Tmed,Vmax,TPrec,Nombre_est,Provincia,Altura,Longitud,Latitud,Población
0,0009X,2013-05-07,25.4,14.6,20,24,0,Alforja,Tarragona,406,411250N,005748E,816.772
1,0009X,2013-05-08,24.3,14.4,19.3,15,0,Alforja,Tarragona,406,411250N,005748E,816.772
2,0009X,2013-05-09,21.6,12.7,17.2,16,1.8,Alforja,Tarragona,406,411250N,005748E,816.772
3,0009X,2013-05-10,21.7,11.4,16.6,29,0,Alforja,Tarragona,406,411250N,005748E,816.772
4,0009X,2013-05-11,22.3,10.8,16.5,26,0,Alforja,Tarragona,406,411250N,005748E,816.772
...,...,...,...,...,...,...,...,...,...,...,...,...,...
133091,9647X,2021-06-26,30.4,14.3,22.3,24,0,Torà,Lleida,435,414821N,012344E,438.517
133092,9647X,2021-06-27,32.2,14.3,23.3,24,0,Torà,Lleida,435,414821N,012344E,438.517
133093,9647X,2021-06-28,29.1,15.4,22.3,24,0,Torà,Lleida,435,414821N,012344E,438.517
133094,9647X,2021-06-29,28.2,11.6,19.9,24,0,Torà,Lleida,435,414821N,012344E,438.517
133095,9647X,2021-06-30,28.2,16.4,22.3,24,0,Torà,Lleida,435,414821N,012344E,438.517

In [82]:
weather_data_population_noNan.isnull().sum()

Identificador_est    0
Fecha                0
Tmax                 0
Tmin                 0
Tmed                 0
Vmax                 0
TPrec                0
Nombre_est           0
Provincia            0
Altura               0
Longitud             0
Latitud              0
Población            0
dtype: int64

In [83]:
weather_data_population_noNan["Fecha"] = pd.to_datetime(weather_data_population_noNan["Fecha"])

In [84]:
weather_data_population_noNan.dtypes

Identificador_est            object
Fecha                datetime64[ns]
Tmax                         object
Tmin                         object
Tmed                         object
Vmax                         object
TPrec                        object
Nombre_est                   object
Provincia                    object
Altura                       object
Longitud                     object
Latitud                      object
Población                    object
dtype: object

In [85]:
weather_data_population_noNan = weather_data_population_noNan.sort_values(["Fecha"])
weather_data_population_noNan

,Identificador_est,Fecha,Tmax,Tmin,Tmed,Vmax,TPrec,Nombre_est,Provincia,Altura,Longitud,Latitud,Población
0,0009X,2013-05-07,25.4,14.6,20,24,0,Alforja,Tarragona,406,411250N,005748E,816.772
48892,2918Y,2013-05-07,18.1,10.7,14.4,24,0.8,El Maíllo,Salamanca,1027,403410N,061325W,329.245
51860,2978X,2013-05-07,18.7,12.7,15.7,19,0.4,Verín,Ourense,380,415536N,072519W,306.650
104314,8416Y,2013-05-07,32.1,16.1,24.1,17,0,Valencia,València/Valencia,11,392850N,002159W,2.591.875
54828,3094B,2013-05-07,23.5,12.5,18,19,0,Tarancón,Cuenca,808,400041N,030117W,196.139
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51859,2918Y,2021-06-30,27.4,8.3,17.8,19,0,El Maíllo,Salamanca,1027,403410N,061325W,329.245
104313,8175,2021-06-30,32.2,16.8,24.5,24,0,Albacete Base Aérea,Albacete,702,385715N,015123W,388.270
54827,2978X,2021-06-30,29.0,7.9,18.5,19,0,Verín,Ourense,380,415536N,072519W,306.650
31228,1730E,2021-06-30,24.2,12.1,18.2,24,0,O Rosal,Pontevedra,55,415638N,085051W,945.408
133095,9647X,2021-06-30,28.2,16.4,22.3,24,0,Torà,Lleida,435,414821N,012344E,438.517

In [86]:
weather_data_population_noNan['Población'] = weather_data_population_noNan['Población'].str.replace('.', '')
weather_data_population_noNan

,Identificador_est,Fecha,Tmax,Tmin,Tmed,Vmax,TPrec,Nombre_est,Provincia,Altura,Longitud,Latitud,Población
0,0009X,2013-05-07,25.4,14.6,20,24,0,Alforja,Tarragona,406,411250N,005748E,816772
48892,2918Y,2013-05-07,18.1,10.7,14.4,24,0.8,El Maíllo,Salamanca,1027,403410N,061325W,329245
51860,2978X,2013-05-07,18.7,12.7,15.7,19,0.4,Verín,Ourense,380,415536N,072519W,306650
104314,8416Y,2013-05-07,32.1,16.1,24.1,17,0,Valencia,València/Valencia,11,392850N,002159W,2591875
54828,3094B,2013-05-07,23.5,12.5,18,19,0,Tarancón,Cuenca,808,400041N,030117W,196139
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51859,2918Y,2021-06-30,27.4,8.3,17.8,19,0,El Maíllo,Salamanca,1027,403410N,061325W,329245
104313,8175,2021-06-30,32.2,16.8,24.5,24,0,Albacete Base Aérea,Albacete,702,385715N,015123W,388270
54827,2978X,2021-06-30,29.0,7.9,18.5,19,0,Verín,Ourense,380,415536N,072519W,306650
31228,1730E,2021-06-30,24.2,12.1,18.2,24,0,O Rosal,Pontevedra,55,415638N,085051W,945408
133095,9647X,2021-06-30,28.2,16.4,22.3,24,0,Torà,Lleida,435,414821N,012344E,438517

In [87]:
weather_data_population_noNan["Tmax"] = pd.to_numeric(weather_data_population_noNan["Tmax"], downcast="float")
weather_data_population_noNan["Tmin"] = pd.to_numeric(weather_data_population_noNan["Tmin"], downcast="float")
weather_data_population_noNan["Tmed"] = pd.to_numeric(weather_data_population_noNan["Tmed"], downcast="float")
weather_data_population_noNan["Vmax"] = pd.to_numeric(weather_data_population_noNan["Vmax"], downcast="float")
weather_data_population_noNan["TPrec"] = pd.to_numeric(weather_data_population_noNan["TPrec"], downcast="float")
weather_data_population_noNan["Altura"] = pd.to_numeric(weather_data_population_noNan["Altura"], downcast="integer")
weather_data_population_noNan["Población"] = pd.to_numeric(weather_data_population_noNan["Población"], downcast="float")
weather_data_population_noNan.dtypes

Identificador_est            object
Fecha                datetime64[ns]
Tmax                        float32
Tmin                        float32
Tmed                        float32
Vmax                        float32
TPrec                       float32
Nombre_est                   object
Provincia                    object
Altura                        int16
Longitud                     object
Latitud                      object
Población                   float32
dtype: object

In [88]:
#from numpy import average
#weather_data_population_noNan_numpy = weather_data_population_noNan.to_numpy()
#weather_data_population_noNan_numpy.average(
#    weather_data_population_noNan_numpy["Tmax"], weights= weather_data_population_noNan_numpy["Población"])

#This is not working
def weighted_mean(df, values, weights, groupby):
    df = df.copy()
    grouped = df.groupby(groupby)
    df['weighted_average'] = df[values] / grouped[weights].transform('sum') * df[weights]
    return grouped['weighted_average'].sum(min_count=1) #min_count is required for Grouper objects

def grouped_weighted_avg(values, weights, by):
        return (values * weights).groupby(by).sum() / weights.groupby(by).sum()

In [89]:
def grouped_weighted_avg_Tmax(values, weights, by):
    return pd.DataFrame((values * weights).groupby(by).sum() / weights.groupby(by).sum(), columns= ["Tmax"])

def grouped_weighted_avg_Tmin(values, weights, by):
    return pd.DataFrame((values * weights).groupby(by).sum() / weights.groupby(by).sum(), columns= ["Tmin"])

In [90]:
weighted_av_Tmax = grouped_weighted_avg_Tmax(values= weather_data_population_noNan["Tmax"],
                         weights= weather_data_population_noNan["Población"],
                         by= weather_data_population_noNan["Fecha"])

weighted_av_Tmax

                 Tmax
Fecha
2013-05-07  26.024410
2013-05-08  25.336803
2013-05-09  23.381573
2013-05-10  22.928568
2013-05-11  22.691177
...               ...
2021-06-26  29.056046
2021-06-27  27.982450
2021-06-28  27.139305
2021-06-29  27.944527
2021-06-30  28.744200

[2968 rows x 1 columns]

In [91]:
weather_data_population_noNan["Tmax"].mean()

20.569137573242188

In [92]:
weighted_av_Tmin = grouped_weighted_avg_Tmin(values= weather_data_population_noNan["Tmin"],
                         weights= weather_data_population_noNan["Población"],
                         by= weather_data_population_noNan["Fecha"])
weighted_av_Tmin

                 Tmin
Fecha
2013-05-07  13.555936
2013-05-08  14.118225
2013-05-09  13.126208
2013-05-10  12.023178
2013-05-11  10.655726
...               ...
2021-06-26  15.605719
2021-06-27  14.947507
2021-06-28  13.948045
2021-06-29  13.623206
2021-06-30  15.174376

[2968 rows x 1 columns]

In [93]:
def grouped_weighted_avg_Tmed(values, weights, by):
    return pd.DataFrame((values * weights).groupby(by).sum() / weights.groupby(by).sum(), columns= ["Tmed"])

def grouped_weighted_avg_Vmax(values, weights, by):
    return pd.DataFrame((values * weights).groupby(by).sum() / weights.groupby(by).sum(), columns= ["Vmax"])

def grouped_weighted_avg_Tprec(values, weights, by):
    return pd.DataFrame((values * weights).groupby(by).sum() / weights.groupby(by).sum(), columns= ["TPrec"])

def grouped_weighted_avg_Altura(values, weights, by):
    return pd.DataFrame((values * weights).groupby(by).sum() / weights.groupby(by).sum(), columns= ["Altura"])

In [94]:
weighted_av_Tmed = grouped_weighted_avg_Tmed(values= weather_data_population_noNan["Tmed"],
                         weights= weather_data_population_noNan["Población"],
                         by= weather_data_population_noNan["Fecha"])

weighted_av_Vmax = grouped_weighted_avg_Vmax(values= weather_data_population_noNan["Vmax"],
                         weights= weather_data_population_noNan["Población"],
                         by= weather_data_population_noNan["Fecha"])

weighted_av_Tprec = grouped_weighted_avg_Tprec(values= weather_data_population_noNan["TPrec"],
                         weights= weather_data_population_noNan["Población"],
                         by= weather_data_population_noNan["Fecha"])

weighted_av_Altura = grouped_weighted_avg_Altura(values= weather_data_population_noNan["Altura"],
                         weights= weather_data_population_noNan["Población"],
                         by= weather_data_population_noNan["Fecha"])

In [95]:
weather_variables_list = [weighted_av_Tmax, weighted_av_Tmin, weighted_av_Tmed,
                          weighted_av_Vmax, weighted_av_Tprec, weighted_av_Altura]

weather_variables = weather_variables_list[0].join(weather_variables_list[1:])
weather_variables

                 Tmax       Tmin       Tmed       Vmax     TPrec      Altura
Fecha
2013-05-07  26.024410  13.555936  19.797901  17.838921  2.095502  388.574585
2013-05-08  25.336803  14.118225  19.728336  15.444501  0.565097  388.574585
2013-05-09  23.381573  13.126208  18.251265  15.949620  1.760222  377.103973
2013-05-10  22.928568  12.023178  17.480787  16.672112  0.249773  377.103973
2013-05-11  22.691177  10.655726  16.671419  15.552441  0.003383  377.103973
...               ...        ...        ...        ...       ...         ...
2021-06-26  29.056046  15.605719  22.344318  21.181517  0.156258  440.388000
2021-06-27  27.982450  14.947507  21.477276  21.588980  0.356326  440.388000
2021-06-28  27.139305  13.948045  20.551270  18.703827  0.131306  440.388000
2021-06-29  27.944527  13.623206  20.784426  16.571365  0.001755  440.388000
2021-06-30  28.744200  15.174376  21.980579  18.588869  0.141748  440.388000

[2968 rows x 6 columns]

In [96]:
weather_variables.rename_axis("Date", axis= "index", inplace=True)
weather_variables

                 Tmax       Tmin       Tmed       Vmax     TPrec      Altura
Date
2013-05-07  26.024410  13.555936  19.797901  17.838921  2.095502  388.574585
2013-05-08  25.336803  14.118225  19.728336  15.444501  0.565097  388.574585
2013-05-09  23.381573  13.126208  18.251265  15.949620  1.760222  377.103973
2013-05-10  22.928568  12.023178  17.480787  16.672112  0.249773  377.103973
2013-05-11  22.691177  10.655726  16.671419  15.552441  0.003383  377.103973
...               ...        ...        ...        ...       ...         ...
2021-06-26  29.056046  15.605719  22.344318  21.181517  0.156258  440.388000
2021-06-27  27.982450  14.947507  21.477276  21.588980  0.356326  440.388000
2021-06-28  27.139305  13.948045  20.551270  18.703827  0.131306  440.388000
2021-06-29  27.944527  13.623206  20.784426  16.571365  0.001755  440.388000
2021-06-30  28.744200  15.174376  21.980579  18.588869  0.141748  440.388000

[2968 rows x 6 columns]

In [97]:
prices2013_brent.set_index("Date", inplace=True)

In [98]:
prices2013_brent.drop("Periodo", inplace= True, axis= 1)

In [99]:
prices2013_brent

,Energía\n final \nMWh,Mercado \ndiario \n€/MWh,Mercado \nintradiario \n€/MWh,Restricciones\n€/MWh,Procesos \nOS \n€/MWh,Garantía potencia \nPagos capacidad\n€/MWh,Total\n€/MWh,Day,Último,Apertura,Máximo,Mínimo,Vol.
Date,,,,,,,,,,,,,
2013-02-01,681911.324,50.75,0.12,3.15,3.18,7.46,64.65,Miércoles,"112,47","111,50","112,90","111,27","183,14K"
2013-03-01,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67,Jueves,"112,14","112,20","112,42","111,63","190,29K"
2013-04-01,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73,Viernes,"111,31","111,72","111,78","110,38","191,33K"
2013-05-01,682149.96,58.11,0.14,1.29,1.43,4.88,65.86,Sábado,"111,31","111,72","111,78","110,38","191,33K"
2013-06-01,647854.785,58.01,0,2.27,2.16,5.02,67.45,Domingo,"111,31","111,72","111,78","110,38","191,33K"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-12-27,663171.045,15.39,0,5.62,5.04,6.82,32.88,Viernes,"112,18","111,95","112,80","111,50","126,91K"
2013-12-28,672714.85,23.98,0.01,5.34,3.21,4.46,37,Sábado,"112,18","111,95","112,80","111,50","126,91K"
2013-12-29,634045.486,42.83,-0.13,5.28,2.88,4.81,55.66,Domingo,"112,18","111,95","112,80","111,50","126,91K"
2013-12-30,634951.745,47.39,-0.57,5.5,4.2,7.33,63.85,Lunes,"111,21","112,20","112,64","110,90","111,07K"
2013-12-31,606765.004,25.26,-0.15,8.44,5.59,6.79,45.93,Martes,"110,80","111,18","111,52","110,40","84,99K"

In [100]:
prices2013_brent.columns

Index(['Energía\n final \nMWh', 'Mercado \ndiario \n€/MWh',
       'Mercado \nintradiario \n€/MWh', 'Restricciones\n€/MWh',
       'Procesos \nOS \n€/MWh', 'Garantía potencia \nPagos capacidad\n€/MWh',
       'Total\n€/MWh', 'Day', 'Último', 'Apertura', 'Máximo', 'Mínimo',
       'Vol.'],
      dtype='object')

In [101]:
prices2013_brent.rename(columns= {"Energía\n final \nMWh": "Energía final MWh", 
                                  "Mercado \ndiario \n€/MWh": "Mercado diario €/MWh",
                                 "Mercado \nintradiario \n€/MWh": "Mercado intradiario €/MWh",
                                 "Restricciones\n€/MWh": "Restricciones €/MWh",
                                 "Procesos \nOS \n€/MWh": "Procesos OS €/MWh",
                                 "Garantía potencia \nPagos capacidad\n€/MWh": "Garantía potencia Pagos capacidad €/MWh",
                                 "Total\n€/MWh": "Total €/MWh"}, inplace=True)

In [102]:
prices2013_brent

,Energía final MWh,Mercado diario €/MWh,Mercado intradiario €/MWh,Restricciones €/MWh,Procesos OS €/MWh,Garantía potencia Pagos capacidad €/MWh,Total €/MWh,Day,Último,Apertura,Máximo,Mínimo,Vol.
Date,,,,,,,,,,,,,
2013-02-01,681911.324,50.75,0.12,3.15,3.18,7.46,64.65,Miércoles,"112,47","111,50","112,90","111,27","183,14K"
2013-03-01,724426.458,57.07,-0.13,1.92,3.47,7.34,69.67,Jueves,"112,14","112,20","112,42","111,63","190,29K"
2013-04-01,717141.532,61.31,-0.08,1.71,2.4,7.39,72.73,Viernes,"111,31","111,72","111,78","110,38","191,33K"
2013-05-01,682149.96,58.11,0.14,1.29,1.43,4.88,65.86,Sábado,"111,31","111,72","111,78","110,38","191,33K"
2013-06-01,647854.785,58.01,0,2.27,2.16,5.02,67.45,Domingo,"111,31","111,72","111,78","110,38","191,33K"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-12-27,663171.045,15.39,0,5.62,5.04,6.82,32.88,Viernes,"112,18","111,95","112,80","111,50","126,91K"
2013-12-28,672714.85,23.98,0.01,5.34,3.21,4.46,37,Sábado,"112,18","111,95","112,80","111,50","126,91K"
2013-12-29,634045.486,42.83,-0.13,5.28,2.88,4.81,55.66,Domingo,"112,18","111,95","112,80","111,50","126,91K"
2013-12-30,634951.745,47.39,-0.57,5.5,4.2,7.33,63.85,Lunes,"111,21","112,20","112,64","110,90","111,07K"
2013-12-31,606765.004,25.26,-0.15,8.44,5.59,6.79,45.93,Martes,"110,80","111,18","111,52","110,40","84,99K"

In [103]:
prices2013_brent_weather = prices2013_brent.merge(weather_variables, on = "Date")
prices2013_brent_weather

,Energía final MWh,Mercado diario €/MWh,Mercado intradiario €/MWh,Restricciones €/MWh,Procesos OS €/MWh,Garantía potencia Pagos capacidad €/MWh,Total €/MWh,Day,Último,Apertura,Máximo,Mínimo,Vol.,Tmax,Tmin,Tmed,Vmax,TPrec,Altura
Date,,,,,,,,,,,,,,,,,,,
2013-06-01,647854.785,58.01,0,2.27,2.16,5.02,67.45,Domingo,"111,31","111,72","111,78","110,38","191,33K",23.668943,10.354040,17.018972,17.428501,0.032273,377.103973
2013-07-01,707896.584,63.42,-0.18,2.45,2.57,7.26,75.52,Lunes,"111,40","111,42","111,69","110,54","203,50K",28.175545,15.590207,21.888693,17.871611,0.453025,384.645233
2013-08-01,792239.818,69,0.08,1.21,1.94,7.43,79.65,Martes,"111,94","111,42","112,47","111,12","194,00K",32.489559,17.869713,25.201107,18.929245,0.019440,377.103973
2013-09-01,813192.864,67.43,0.05,1.74,1.08,7.32,77.62,Miércoles,"111,76","111,90","112,23","111,11","171,95K",28.972286,15.209291,22.091158,16.862797,0.000000,385.403412
2013-10-01,821426.583,66.12,0.09,1.45,1.63,7.17,76.45,Jueves,"111,89","111,68","113,29","111,60","196,97K",26.928795,17.778019,22.348431,18.120661,2.559554,385.403412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-12-27,663171.045,15.39,0,5.62,5.04,6.82,32.88,Viernes,"112,18","111,95","112,80","111,50","126,91K",14.972183,6.814744,10.901595,20.926922,2.394948,385.403412
2013-12-28,672714.85,23.98,0.01,5.34,3.21,4.46,37,Sábado,"112,18","111,95","112,80","111,50","126,91K",13.374936,4.452909,8.915764,24.365299,2.491523,385.403412
2013-12-29,634045.486,42.83,-0.13,5.28,2.88,4.81,55.66,Domingo,"112,18","111,95","112,80","111,50","126,91K",11.291446,2.104122,6.691592,17.161993,0.205239,385.403412
2013-12-30,634951.745,47.39,-0.57,5.5,4.2,7.33,63.85,Lunes,"111,21","112,20","112,64","110,90","111,07K",12.021042,1.110683,6.578516,15.843420,1.099209,385.403412
2013-12-31,606765.004,25.26,-0.15,8.44,5.59,6.79,45.93,Martes,"110,80","111,18","111,52","110,40","84,99K",12.720055,2.847992,7.781052,16.840603,1.675617,385.403412

It seems that we don't have weather data for all days of the year (now looking at 2013 only)

In [104]:
weather_variables_2013 = weather_variables.loc['2013-01-01':'2013-12-31']
weather_variables_2013

                 Tmax       Tmin       Tmed       Vmax     TPrec      Altura
Date
2013-05-07  26.024410  13.555936  19.797901  17.838921  2.095502  388.574585
2013-05-08  25.336803  14.118225  19.728336  15.444501  0.565097  388.574585
2013-05-09  23.381573  13.126208  18.251265  15.949620  1.760222  377.103973
2013-05-10  22.928568  12.023178  17.480787  16.672112  0.249773  377.103973
2013-05-11  22.691177  10.655726  16.671419  15.552441  0.003383  377.103973
...               ...        ...        ...        ...       ...         ...
2013-12-27  14.972183   6.814744  10.901595  20.926922  2.394948  385.403412
2013-12-28  13.374936   4.452909   8.915764  24.365299  2.491523  385.403412
2013-12-29  11.291446   2.104122   6.691592  17.161993  0.205239  385.403412
2013-12-30  12.021042   1.110683   6.578516  15.843420  1.099209  385.403412
2013-12-31  12.720055   2.847992   7.781052  16.840603  1.675617  385.403412

[238 rows x 6 columns]

In [105]:
new_index_2013 = pd.date_range(start='2013-01-01', end='2013-12-31')

In [106]:
weather_variables_2013 = weather_variables_2013.reindex(new_index_2013)
weather_variables_2013

                 Tmax      Tmin       Tmed       Vmax     TPrec      Altura
2013-01-01        NaN       NaN        NaN        NaN       NaN         NaN
2013-01-02        NaN       NaN        NaN        NaN       NaN         NaN
2013-01-03        NaN       NaN        NaN        NaN       NaN         NaN
2013-01-04        NaN       NaN        NaN        NaN       NaN         NaN
2013-01-05        NaN       NaN        NaN        NaN       NaN         NaN
...               ...       ...        ...        ...       ...         ...
2013-12-27  14.972183  6.814744  10.901595  20.926922  2.394948  385.403412
2013-12-28  13.374936  4.452909   8.915764  24.365299  2.491523  385.403412
2013-12-29  11.291446  2.104122   6.691592  17.161993  0.205239  385.403412
2013-12-30  12.021042  1.110683   6.578516  15.843420  1.099209  385.403412
2013-12-31  12.720055  2.847992   7.781052  16.840603  1.675617  385.403412

[365 rows x 6 columns]

In [107]:
weather_variables_2013["Tmax"].isnull().sum()

127

In [108]:
weather_variables_2013.isnull().values.any()

True

In [109]:
pd.options.display.max_rows=365
nan_rows2013 = weather_variables_2013[weather_variables_2013.isnull().any(1)]
nan_rows2013

            Tmax  Tmin  Tmed  Vmax  TPrec  Altura
2013-01-01   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-02   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-03   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-04   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-05   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-06   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-07   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-08   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-09   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-10   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-11   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-12   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-13   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-14   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-15   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-16   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-17   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-18   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-19   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-20   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-21   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-22   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-23   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-24   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-25   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-26   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-27   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-28   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-29   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-30   NaN   NaN   NaN   NaN    NaN     NaN
2013-01-31   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-01   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-02   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-03   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-04   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-05   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-06   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-07   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-08   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-09   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-10   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-11   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-12   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-13   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-14   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-15   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-16   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-17   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-18   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-19   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-20   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-21   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-22   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-23   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-24   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-25   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-26   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-27   NaN   NaN   NaN   NaN    NaN     NaN
2013-02-28   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-01   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-02   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-03   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-04   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-05   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-06   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-07   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-08   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-09   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-10   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-11   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-12   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-13   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-14   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-15   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-16   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-17   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-18   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-19   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-20   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-21   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-22   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-23   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-24   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-25   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-26   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-27   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-28   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-29   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-30   NaN   NaN   NaN   NaN    NaN     NaN
2013-03-31   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-01   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-02   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-03   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-04   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-05   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-06   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-07   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-08   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-09   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-10   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-11   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-12   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-13   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-14   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-15   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-16   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-17   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-18   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-19   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-20   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-21   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-22   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-23   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-24   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-25   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-26   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-27   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-28   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-29   NaN   NaN   NaN   NaN    NaN     NaN
2013-04-30   NaN   NaN   NaN   NaN    NaN     NaN
2013-05-01   NaN   NaN   NaN   NaN    NaN     NaN
2013-05-02   NaN   NaN   NaN   NaN    NaN     NaN
2013-05-03   NaN   NaN   NaN   NaN    NaN     NaN
2013-05-04   NaN   NaN   NaN   NaN    NaN     NaN
2013-05-05   NaN   NaN   NaN   NaN    NaN     NaN
2013-05-06   NaN   NaN   NaN   NaN    NaN     NaN
2013-11-21   NaN   NaN   NaN   NaN    NaN     NaN

So it looks like we're missing Jan-May from 2013 (this was already specified in the database)

In [110]:
import seaborn as sns
import matplotlib.pyplot as plt

In [111]:
prices2013_brent_weather

,Energía final MWh,Mercado diario €/MWh,Mercado intradiario €/MWh,Restricciones €/MWh,Procesos OS €/MWh,Garantía potencia Pagos capacidad €/MWh,Total €/MWh,Day,Último,Apertura,Máximo,Mínimo,Vol.,Tmax,Tmin,Tmed,Vmax,TPrec,Altura
Date,,,,,,,,,,,,,,,,,,,
2013-06-01,647854.785,58.01,0,2.27,2.16,5.02,67.45,Domingo,"111,31","111,72","111,78","110,38","191,33K",23.668943,10.354040,17.018972,17.428501,0.032273,377.103973
2013-07-01,707896.584,63.42,-0.18,2.45,2.57,7.26,75.52,Lunes,"111,40","111,42","111,69","110,54","203,50K",28.175545,15.590207,21.888693,17.871611,0.453025,384.645233
2013-08-01,792239.818,69,0.08,1.21,1.94,7.43,79.65,Martes,"111,94","111,42","112,47","111,12","194,00K",32.489559,17.869713,25.201107,18.929245,0.019440,377.103973
2013-09-01,813192.864,67.43,0.05,1.74,1.08,7.32,77.62,Miércoles,"111,76","111,90","112,23","111,11","171,95K",28.972286,15.209291,22.091158,16.862797,0.000000,385.403412
2013-10-01,821426.583,66.12,0.09,1.45,1.63,7.17,76.45,Jueves,"111,89","111,68","113,29","111,60","196,97K",26.928795,17.778019,22.348431,18.120661,2.559554,385.403412
2013-11-01,798185.741,72.41,-0.07,0.84,1.05,7.2,81.41,Viernes,"110,64","111,95","111,95","109,60","168,07K",20.394932,6.742206,13.568150,15.295473,0.612992,385.403412
2013-12-01,740278.669,54,0.03,1.51,1.52,4.71,61.76,Sábado,"110,64","111,95","111,95","109,60","168,07K",11.868778,1.686204,6.785467,19.376122,0.651977,377.103973
2013-06-02,828424.928,20.32,0.12,4.05,2.05,6.8,33.34,Miércoles,"116,73","116,45","117,05","115,72","207,78K",24.427149,10.862791,17.655333,16.105844,0.095098,377.103973
2013-07-02,815307.458,42.85,-0.2,3.51,3.16,6.97,56.29,Jueves,"117,24","116,90","117,83","116,71","242,30K",27.890429,16.392912,22.157217,17.191790,0.159738,384.645233
2013-08-02,798919.17,37.96,0.03,3.62,2.53,7.02,51.16,Viernes,"118,90","117,48","119,17","117,31","206,48K",31.423157,18.279638,24.856649,17.697090,0.185734,377.103973
2013-09-02,737447.516,50.7,-0.3,2.97,2.91,4.48,60.76,Sábado,"118,90","117,48","119,17","117,31","206,48K",29.123348,15.181919,22.153080,17.003183,0.000000,385.403412
2013-10-02,740805.753,28.47,-0.08,3.49,2.52,4.44,38.83,Domingo,"118,90","117,48","119,17","117,31","206,48K",28.243448,16.812334,22.526052,15.644508,1.578871,385.403412
2013-11-02,807179.43,35,-0.19,3.98,3.76,7.13,49.68,Lunes,"118,13","118,90","119,07","117,54","141,28K",23.138014,9.763537,16.459875,15.518935,3.152200,385.403412
2013-12-02,813056.864,48,-0.41,2.81,2.03,6.96,59.4,Martes,"118,66","118,27","118,90","117,81","98,00K",11.822379,0.640631,6.239425,14.798102,0.003367,377.103973
2013-06-03,769434.261,47.92,-0.23,2.4,2.37,5.65,58.11,Miércoles,"111,06","111,83","112,23","110,46","201,77K",24.548843,10.589724,17.564770,16.795956,0.000911,377.103973
2013-07-03,800752.3,31.86,-0.31,3.21,1.77,5.4,41.93,Jueves,"111,15","111,08","111,40","110,41","213,07K",30.061279,16.583950,23.315008,16.031092,0.035267,377.103973
2013-08-03,767836.048,23.96,-0.01,3.72,2.09,5.29,35.05,Viernes,"110,85","110,90","111,33","109,14","228,95K",30.595512,18.453020,24.526106,15.786689,0.041226,377.103973
2013-09-03,728998.464,13.12,-0.08,3.56,1.93,4.12,22.64,Sábado,"110,85","110,90","111,33","109,14","228,95K",29.594769,14.907179,22.249866,15.597408,0.002681,385.403412
2013-10-03,694548.763,4.97,-0.04,3.16,1.48,4.24,13.82,Domingo,"110,85","110,90","111,33","109,14","228,95K",25.798780,17.949080,21.874535,16.530462,2.493136,385.403412
2013-11-03,791692.512,6.56,-0.12,4.8,1.67,5.37,18.28,Lunes,"110,22","110,67","110,72","109,53","164,82K",21.131552,9.349448,15.237434,16.915697,0.813250,385.403412
2013-12-03,782814.147,42.84,-0.78,3.68,3.15,5.51,54.4,Martes,"109,65","110,13","111,20","109,30","146,00K",14.324610,1.888919,8.105398,13.167189,0.340360,377.103973
2013-06-04,697428.763,1.49,-0.03,4.3,2.26,4.02,12.04,Sábado,"104,12","106,49","106,65","103,62","273,97K",25.570965,10.594288,18.100410,17.401459,0.079021,377.103973
2013-07-04,655741.565,2.61,-0.04,5.06,2.79,4.16,14.58,Domingo,"104,12","106,49","106,65","103,62","273,97K",31.036018,18.111425,24.567547,18.160860,0.008629,377.103973
2013-08-04,755030.241,2.62,-0.03,5.38,2.12,5.26,15.35,Lunes,"104,66","104,28","105,55","103,40","245,68K",32.266048,16.963131,24.621271,15.274786,0.018486,377.103973
2013-09-04,764187.928,3.72,-0.05,5.52,1.96,5.14,16.3,Martes,"106,23","104,78","106,50","104,27","173,29K",29.206272,14.997565,22.102697,16.313297,0.000000,385.403412
2013-10-04,764352.285,3.87,-0.03,6.29,1.38,5.1,16.6,Miércoles,"105,79","106,19","106,47","105,16","136,06K",24.964466,16.252335,20.620159,15.128667,8.142433,385.403412
2013-11-04,753112.64,1.46,-0.02,5.24,1.03,5.1,12.82,Jueves,"104,27","105,50","105,94","103,70","116,87K",17.649477,10.650826,14.152673,23.743452,4.713278,385.403412
2013-12-04,741292.015,8.4,0.2,5.74,1.96,5.11,21.4,Viernes,"103,11","104,29","104,39","101,09","121,49K",15.891443,2.131193,9.003471,12.336765,0.010085,377.103973
2013-06-05,669760.041,53.7,-0.31,2.07,1,5.54,62.01,Lunes,"105,46","104,25","105,54","103,89","135,08K",25.014675,11.890494,18.443727,17.090515,0.233637,377.103973
2013-07-05,711755.115,45.17,-0.3,2.29,0.59,5.2,52.95,Martes,"104,40","105,40","105,94","104,00","264,56K",31.248274,17.323647,24.303083,19.116756,0.019146,377.103973
2013-08-05,706886.07,50.05,-0.48,3.03,1.13,5.23,58.96,Miércoles,"104,34","104,11","104,80","103,53","229,32K",31.587910,18.228405,24.915775,15.710987,0.002100,377.103973
2013-09-05,712014.927,51.04,-0.41,1.34,0.76,5.2,57.94,Jueves,"104,47","104,44","104,60","103,45","197,07K",28.024578,15.402828,21.737352,17.462345,0.893780,385.403412
2013-10-05,707860.407,46.06,-0.18,1.35,1.23,5.18,53.64,Viernes,"103,91","104,35","104,45","101,56","215,45K",24.882433,13.742122,19.318340,14.731571,0.383772,385.403412
2013-11-05,623204.71,46.15,-0.29,2.4,1.23,4.11,53.6,Sábado,"103,91","104,35","104,45","101,56","215,45K",21.387884,13.474569,17.431805,22.904749,1.720795,377.103973
2013-12-05,632133.052,33.07,-0.55,3.52,1.45,3.89,41.38,Domingo,"103,91","104,35","104,45","101,56","215,45K",14.983517,2.499691,8.739937,14.310185,0.010469,377.103973
2013-05-13,686433.383,46.65,-0.07,2.57,1.21,5.39,55.75,Lunes,"102,82","103,26","103,86","102,25","173,55K",23.260569,10.292131,16.772802,16.880873,0.083975,377.103973
2013-05-14,698634.003,49.11,-0.3,2.43,1.12,5.25,57.62,Martes,"102,60","102,82","103,10","101,96","160,03K",21.664877,11.887777,16.779800,18.854889,2.884115,377.103973
2013-05-15,692788.276,36.4,-0.14,3.52,1.09,5.17,46.05,Miércoles,"103,68","102,70","103,82","101,20","106,54K",18.662067,9.953674,14.296206,18.417933,7.492735,377.103973
2013-05-16,690805.931,39.9,-0.05,3.71,1.73,5.27,50.56,Jueves,"103,80","103,74","104,40","102,95","26,35K",17.611048,7.824580,12.726688,21.581022,2.172261,377.103973
2013-05-17,670740.647,41.7,0.04,2.79,1.96,5.33,51.82,Viernes,"104,64","103,87","104,87","103,35","193,73K",16.443428,7.566709,11.997943,21.085617,5.583970,377.103973
2013-05-18,649201.065,28.4,-0.16,4.75,1.83,3.97,38.79,Sábado,"104,64","103,87","104,87","103,35","193,73K",16.259045,7.564321,11.908356,23.821142,7.874939,377.103973
2013-05-19,596988.451,40.13,-0.22,3.79,2.07,4.19,49.96,Domingo,"104,64","103,87","104,87","103,35","193,73K",16.588238,7.739380,12.166773,22.348059,7.089354,377.103973
2013-05-20,662189.7,50.02,-0.15,4.01,1.22,5.46,60.56,Lunes,"104,80","104,75","105,31","103,83","164,96K",16.394352,7.270356,11.849190,14.413983,3.524224,377.103973
2013-05-21,695053.129,50.91,0.03,2.7,1.37,5.29,60.29,Martes,"103,91","104,78","105,15","103,51","179,06K",17.336624,7.319803,12.324626,16.596504,1.248702,377.103973
2013-05-22,725968.867,41.94,-0.05,3.39,0.91,5.09,51.28,Miércoles,"102,60","103,52","103,79","102,22","207,42K",22.873703,9.102480,15.995220,18.283140,0.244128,377.103973
2013-05-23,732272.081,41.97,-0.19,3.36,0.74,5.03,50.91,Jueves,"102,44","102,25","102,68","100,64","230,37K",22.506735,9.860977,16.182747,19.772875,0.178501,377.103973
2013-05-24,711949.134,42.08,-0.25,5.01,1.48,5.06,53.38,Viernes,"102,64","102,55","102,79","101,65","136,63K",21.044716,9.292377,15.164415,19.908340,0.160730,377.103973
2013-05-25,643888.31,40.35,-0.38,4.79,0.92,3.98,49.65,Sábado,"102,64","102,55","102,79","101,65","136,63K",21.323427,9.502976,15.419663,18.300388,0.156358,377.103973
2013-05-26,591562.722,41.06,-0.29,5.41,0.81,4.16,51.15,Domingo,"102,64","102,55","102,79","101,65","136,63K",20.867960,9.199719,15.035291,18.223101,0.331795,377.103973
2013-05-27,672740.502,48.09,0.04,4.38,1.28,5.45,59.24,Lunes,"102,62","102,52","102,65","102,10","21,12K",19.930548,10.543351,15.252711,17.896164,2.246832,377.103973
2013-05-28,703632.106,43.11,-0.27,3.6,0.91,5.17,52.52,Martes,"104,23","102,51","104,69","102,48","195,12K",19.807770,9.020401,14.409451,21.131742,1.429489,377.103973
2013-05-29,708537.437,38.41,0,4.18,0.92,5.17,48.69,Miércoles,"102,43","104,32","104,37","102,17","209,65K",19.276508,8.909042,14.098575,23.828890,1.985421,377.103973
2013-05-30,680266.269,43.85,0,3.94,1.07,5.22,54.07,Jueves,"102,19","102,40","102,85","101,08","232,91K",20.756824,8.697157,14.738402,20.231947,1.123885,377.103973
2013-05-31,694708.876,41.27,-0.26,3.83,0.97,5.12,50.93,Viernes,"100,39","102,12","102,38","100,03","215,28K",22.141874,10.319066,16.219282,19.443481,0.190871,377.103973
2013-06-06,700746.514,49.47,-0.32,2.35,0.67,5.44,57.6,Jueves,"103,61","102,94","103,95","102,81","173,41K",23.591663,12.311874,17.948832,17.482946,0.832460,377.103973
2013-07-06,688082.805,49.33,-0.16,2.24,0.99,5.42,57.82,Viernes,"104,56","103,65","105,01","102,89","234,18K",31.749016,17.545542,24.647614,17.815912,0.005683,377.103973
2013-08-06,629211.728,45.96,-0.51,2.62,1.39,4.05,53.52,Sábado,"104,56","103,65","105,01","102,89","234,18K",31.260399,18.747427,25.011953,17.103132,0.481825,377.103973
2013-09-06,627979.255,36.55,-0.98,3.73,1.5,3.89,44.67,Domingo,"104,56","103,65","105,01","102,89","234,18K",27.414257,15.051105,21.238297,15.583774,1.340281,385.403412
2013-10-06,692355.479,45.93,-0.18,3.29,1.28,5.53,55.86,Lunes,"103,95","104,56","104,76","103,66","159,65K",24.369707,13.451190,18.900633,13.745204,0.549777,385.403412
2013-11-06,731935.856,46.9,-0.51,2.33,1.25,5.3,55.27,Martes,"102,96","103,89","103,89","101,82","156,14K",24.023424,12.354382,18.190687,17.458525,0.497921,377.103973
2013-12-06,734587.924,50.55,-0.53,2.06,1.27,5.45,58.81,Miércoles,"103,49","102,56","104,10","102,23","94,92K",14.159845,1.574487,7.862342,15.631867,0.000000,377.103973
2013-06-13,744721.7,47.84,-0.42,3.16,0.94,5.46,56.98,Jueves,"104,25","103,33","104,26","102,75","21,31K",29.135796,15.893536,22.520584,16.258902,0.548861,377.103973
2013-06-14,736213.556,45.96,-0.31,1.89,1.43,5.48,54.45,Viernes,"105,93","104,95","106,64","104,46","197,14K",29.007936,15.457652,22.233643,16.599670,0.045039,384.645233
2013-06-15,653929.7,46.9,-0.19,1.47,1.19,4.27,53.63,Sábado,"105,93","104,95","106,64","104,46","197,14K",29.253494,15.165089,22.217896,15.466918,0.000000,384.645233
2013-06-16,635841.927,39.56,-0.32,3.92,2.01,4.18,49.35,Domingo,"105,93","104,95","106,64","104,46","197,14K",30.131630,15.345557,22.750578,16.219193,1.236493,377.103973
2013-06-17,698317.938,42.86,-0.13,3.73,1.67,7.67,55.8,Lunes,"105,47","105,77","106,67","105,28","160,18K",25.872875,15.385049,20.637014,18.073496,2.933959,377.103973
2013-06-18,695498.031,47.08,-0.04,2.14,1.4,7.45,58.03,Martes,"106,02","105,66","106,24","105,11","150,87K",23.106567,14.078074,18.590801,19.009912,4.911742,384.645233
2013-06-19,704674.111,48.27,-0.41,1.68,1.45,7.33,58.32,Miércoles,"106,12","106,10","106,59","105,45","164,86K",22.114515,12.800696,17.451483,17.427235,3.031955,384.645233
2013-06-20,700360.223,49.66,0.11,1.63,1.19,7.46,60.05,Jueves,"102,15","105,62","105,62","101,75","301,24K",24.756838,12.258746,18.508001,16.647139,0.640241,384.645233
2013-06-21,685940.468,50.09,-0.21,1.63,1.1,7.5,60.11,Viernes,"100,91","102,10","103,09","100,04","263,37K",25.409840,13.391890,19.413708,16.293898,1.589941,384.645233
2013-06-22,644317.226,47.77,-0.35,1.51,1.42,4.18,54.54,Sábado,"100,91","102,10","103,09","100,04","263,37K",26.923216,13.036941,19.989471,17.692829,0.337168,384.645233
2013-06-23,651633.885,24.4,-0.35,3.82,1.98,3.93,33.78,Domingo,"100,91","102,10","103,09","100,04","263,37K",26.821522,14.390704,20.600912,17.441629,0.288986,384.645233
2013-06-24,686205.586,25.55,0.1,4.55,2.35,6.94,39.48,Lunes,"101,16","100,61","101,64","99,67","254,19K",25.996792,13.807088,19.913115,17.534290,0.023999,384.645233
2013-06-25,726343.867,38.92,-0.08,2.95,1.74,7.25,50.77,Martes,"101,26","101,00","102,08","100,70","182,09K",26.463154,13.962914,20.211134,18.058065,0.023999,384.645233
2013-06-26,735672.778,38.5,-0.15,2.93,1.37,7.25,49.89,Miércoles,"101,66","101,10","101,89","100,25","195,23K",26.594109,14.257314,20.433628,19.056566,0.023999,384.645233
2013-06-27,750696.371,35.67,0.25,3.84,1.67,7.15,48.57,Jueves,"102,82","101,66","103,34","101,66","190,61K",26.599159,13.675590,20.145943,19.384769,0.087814,384.645233
2013-06-28,731555.603,40.47,-0.13,2.9,1.68,7.21,52.13,Viernes,"102,16","102,76","103,44","101,87","230,25K",26.724018,14.344958,20.546194,18.931477,0.023999,384.645233
2013-06-29,688068.041,31.43,-0.15,3.21,1.74,4.02,40.25,Sábado,"102,16","102,76","103,44","101,87","230,25K",28.362160,14.886827,21.633278,18.818365,0.023999,384.645233
2013-06-30,652965.176,29.2,0.04,4.46,2.23,4.02,39.96,Domingo,"102,16","102,76","103,44","101,87","230,25K",28.768950,14.771976,21.779064,17.740639,0.013002,384.645233
2013-05-07,794946.024,44.61,-0.05,1.63,1.37,7.25,54.82,Viernes,"107,72","105,54","107,88","105,38","233,34K",26.024410,13.555936,19.797901,17.838921,2.095502,388.574585
2013-06-07,729433.261,44.02,0.1,1.35,1.35,4.16,50.98,Sábado,"107,72","105,54","107,88","105,38","233,34K",22.069284,12.388698,17.210234,17.354637,2.014410,377.103973
2013-07-07,683462.151,39.36,0.02,2.69,1.23,4.25,47.55,Domingo,"107,72","105,54","107,88","105,38","233,34K",32.610058,17.148808,24.881357,17.860518,0.000000,377.103973
2013-08-07,785653.806,46.89,0.06,2.01,1.26,7.51,57.74,Lunes,"107,43","108,00","108,04","106,79","185,82K",29.954096,17.642115,23.798635,17.836092,1.605204,377.103973
2013-09-07,808218.964,48.66,0.08,1.34,1.26,7.4,58.75,Martes,"107,81","107,27","108,26","106,85","163,66K",23.528032,16.182978,19.856903,16.903561,9.321280,385.403412
2013-10-07,814222.205,50.9,0.12,1.51,1.19,7.37,61.09,Miércoles,"108,51","108,12","108,69","107,71","199,70K",24.129810,13.058873,18.594086,13.913193,0.264221,385.403412
2013-11-07,799937.436,54.48,0.02,1.09,1.12,7.43,64.14,Jueves,"107,73","108,24","108,93","107,02","184,69K",21.125750,10.895555,16.008854,13.565160,0.664131,377.103973
2013-12-07,801405.867,62.44,0.03,0.84,1.12,7.32,71.74,Viernes,"108,81","107,33","109,14","107,28","127,81K",14.743750,0.847899,7.792244,12.309163,0.002533,377.103973
2013-07-13,738911.14,58.84,-0.18,0.63,1.05,4.12,64.46,Sábado,"108,81","107,33","109,14","107,28","127,81K",30.603497,17.922369,24.275372,16.962339,0.772672,377.103973
2013-07-14,679247.412,54,-0.25,0.98,1.51,4.13,60.38,Domingo,"108,81","107,33","109,14","107,28","127,81K",30.181479,17.449585,23.814013,17.867100,0.811590,377.103973
2013-07-15,779527.377,57.07,0.02,0.88,1.42,7.49,66.89,Lunes,"109,09","108,99","109,26","107,96","100,86K",30.847519,16.822006,23.822460,15.464972,0.379832,377.103973
2013-07-16,799116.821,56.99,-0.05,0.73,1.22,7.31,66.21,Martes,"109,40","109,05","109,72","108,63","19,97K",31.450785,17.613720,24.520689,17.032660,0.555134,377.103973
2013-07-17,804401.726,56.57,-0.07,0.78,1.34,7.32,65.95,Miércoles,"108,61","107,90","108,74","107,30","183,57K",31.859251,17.745790,24.799719,15.526292,0.357565,377.103973
2013-07-18,797355.918,54.8,-0.01,0.83,1.08,7.37,64.07,Jueves,"108,70","108,63","108,87","108,03","196,44K",30.791279,17.358711,24.083717,17.568863,2.327734,377.103973
2013-07-19,784717.207,57.35,-0.07,0.87,1.15,7.41,66.72,Viernes,"108,07","108,73","109,18","107,01","212,19K",30.814896,18.058107,24.438406,16.387278,0.451272,377.103973
2013-07-20,710827.105,51.31,0.02,0.73,1.18,4.25,57.49,Sábado,"108,07","108,73","109,18","107,01","212,19K",30.751600,18.071383,24.398323,17.312216,0.144860,377.103973
2013-07-21,662376.141,50.55,-0.04,1.17,1.51,4.23,57.42,Domingo,"108,07","108,73","109,18","107,01","212,19K",30.557461,18.003952,24.276405,16.572361,0.220320,377.103973
2013-07-22,760238.196,58.19,-0.05,0.84,1.21,7.68,67.87,Lunes,"108,15","108,30","108,68","107,55","198,42K",31.139000,17.905174,24.539152,16.616531,0.206810,377.103973
2013-07-23,784820.531,57.74,-0.03,0.73,1.04,7.47,66.95,Martes,"108,42","108,30","108,63","107,56","190,20K",30.963881,17.971411,24.468809,17.287245,0.497374,377.103973
2013-07-24,785119.417,57.18,0.03,0.77,1.1,7.49,66.57,Miércoles,"107,19","108,44","108,60","106,25","197,80K",31.925495,18.499815,25.221111,15.688317,0.008104,377.103973
2013-07-25,782591.659,58.6,-0.32,0.57,1.11,7.27,67.23,Jueves,"107,65","107,11","107,87","106,54","176,11K",32.025276,18.820894,25.427160,16.704048,0.491281,377.103973
2013-07-26,779071.685,54.88,-0.13,0.97,1.06,7.27,64.05,Viernes,"107,17","107,59","107,79","106,53","119,94K",30.996758,18.271017,24.642654,16.113237,0.126379,377.103973
2013-07-27,700831.254,47.15,-0.14,1.31,1.84,4.27,54.41,Sábado,"107,17","107,59","107,79","106,53","119,94K",29.230202,18.353479,23.798048,17.446667,0.662260,377.103973
2013-07-28,656936.077,32.31,-0.1,3.22,2.2,4.21,41.84,Domingo,"107,17","107,59","107,79","106,53","119,94K",29.778246,18.024164,23.891346,19.227703,0.682499,377.103973
2013-07-29,739635.474,51.32,0.03,1.48,2.14,7.33,62.31,Lunes,"107,45","107,19","107,89","106,60","178,93K",29.729359,16.061733,22.907705,16.851540,0.479741,377.103973
2013-07-30,745845.376,54.76,-0.1,1.16,1.28,7.33,64.44,Martes,"106,91","107,45","107,56","106,54","160,00K",30.900133,15.760450,23.328079,16.635674,0.000000,377.103973
2013-07-31,751266.787,52.01,-0.27,1.82,1.07,7.31,61.95,Miércoles,"107,70","106,84","107,95","105,73","222,57K",32.822796,17.166195,24.998398,18.647615,0.000000,377.103973
2013-05-08,717983.151,51.49,0.01,2.17,1.51,4.85,60.03,Lunes,"108,70","109,09","109,44","107,55","168,83K",25.336803,14.118225,19.728336,15.444501,0.565097,388.574585
2013-06-08,727242.056,51.74,-0.09,1.86,1.23,4.74,59.47,Martes,"108,18","108,74","109,23","107,46","229,16K",19.958273,11.268795,15.613201,18.941666,2.893028,377.103973
2013-07-08,719678.081,48.63,-0.1,1.78,1.14,4.66,56.1,Miércoles,"107,44","108,07","108,16","107,07","208,43K",32.419624,17.946690,25.190161,18.528957,0.017093,377.103973
2013-08-08,711279.62,49.37,-0.15,2.11,1.06,4.54,56.92,Jueves,"106,68","107,39","107,86","105,85","175,73K",28.758352,16.014235,22.406786,17.610697,0.992515,377.103973
2013-09-08,716106.463,48.19,-0.12,1.48,1.01,4.54,55.1,Viernes,"108,22","106,81","108,32","106,60","148,43K",26.156300,14.265777,20.201944,14.955901,3.670771,385.403412
2013-10-08,663807.423,43.73,-0.17,2.13,1.41,4.25,51.36,Sábado,"108,22","106,81","108,32","106,60","148,43K",24.284554,12.384393,18.336634,14.196334,0.256466,385.403412
2013-11-08,625436.354,41.15,-0.19,2.6,1.75,4.23,49.54,Domingo,"108,22","106,81","108,32","106,60","148,43K",20.317581,9.729219,15.031846,18.802174,1.091638,377.103973
2013-12-08,713954.716,47.22,0.09,1.75,1.49,4.67,55.21,Lunes,"108,97","108,13","109,13","107,43","147,83K",13.570186,-0.119855,6.715229,11.089088,0.006870,377.103973
2013-08-13,724966.999,44.17,0.05,1.62,1.39,4.54,51.78,Martes,"109,82","109,08","110,06","108,95","112,23K",31.386091,18.165577,24.773146,16.655991,0.807313,385.403412
2013-08-14,719532.306,47.37,-0.03,1.95,1.46,4.55,55.3,Miércoles,"110,20","109,51","110,36","109,05","97,93K",31.093939,18.104811,24.605957,17.249702,0.697364,385.403412
2013-08-15,654317.649,47.82,-0.12,1.29,1.57,4.25,54.81,Jueves,"111,11","110,35","111,53","110,35","19,27K",31.333345,17.885775,24.617128,16.377296,0.616711,385.403412
2013-08-16,666751.02,49.48,0.11,1.53,2.01,4.73,57.87,Viernes,"110,40","109,42","110,70","109,17","195,85K",31.439693,18.269283,24.862131,17.097670,3.102891,385.403412